#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     evm-wallet.js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public
 *     License along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* LibEVM writable globals */

  /* global
       wallet_name:
         writable */

/* eslint-disable
     no-unused-vars */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _argv_url_get */
const
  _argv_url_get =
    _libcrash._argv_url_get;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _echo */
const
  _echo =
    _libcrash._echo;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _get */
const
  _get =
    _libcrash._get;
/* global
     _global_get */
const
  _global_get =
    _libcrash._global_get;
/* global
     _homedir_get */
const
  _homedir_get =
    _libcrash._homedir_get;
/* global
     _get_date_human */
const
  _get_date_human =
    _libcrash._get_date_human;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _require */
const
  _require =
    _libcrash._require;
/* global
     _set */
const
  _set =
    _libcrash._set;
const
  _libevm_wallet =
    await import(
      "./libevm-wallet");
/* global
     _evm_wallet:
       writable */
const
  _evm_wallet =
    _libevm_wallet._evm_wallet;
const
  _libevm_module =
    await _require(
      "libevm");
/* global
     _libevm_cmdline_parse */
const
  _libevm_cmdline_parse =
    _libevm_module._libevm_cmdline_parse;
/* global
     _libevm_global_variables */
const
  _libevm_global_variables =
    _libevm_module._libevm_global_variables;
/* global
     _libevm_url_parse */
const
  _libevm_url_parse =
    _libevm_module._libevm_url_parse;
/* global
     _wallet_overrides_set */
const
  _wallet_overrides_set =
    _libevm_module._wallet_overrides_set;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  _set(
    "app",
    "name",
    "evm-wallet.js");
  /* global
       runtime_environment:
         writable */
  _set(
    "runtime",
    "environment",
    "");
  /* global
       app_opts:
         writable */
  _set(
    "app",
    "opts",
    []);
  /* global
       call_date:
         writable */
  _set(
    "call",
    "date",
    "");
  /* global
       config_dir:
         writable */
  _set(
    "config",
    "dir",
    "");
  /* global
       cache_dir:
         writable */
  _set(
    "cache",
    "dir",
    "");
  /* global
       tasks_parallel:
         writable */
  _set(
    "tasks",
    "parallel",
    "");
  /* global
       target_networks:
         writable */
  _set(
    "target",
    "networks",
    []);
  /* global
       target_command:
         writable */
  _set(
    "target",
    "command",
    "");
  /* global
       target_key:
         writable */
  _set(
    "target",
    "key",
    "");
  /* global
       target_value:
         writable */
  _set(
    "target",
    "value",
    "");
  /* global
       output_type:
         writable */
  _set(
    "output",
    "type",
    "");
  /* global
       currency_type:
         writable */
  _set(
    "currency",
    "type",
    "");
  /* global
       currency_address:
         writable */
  _set(
    "currency",
    "address",
    "");
  /* global
       networks_all:
         writable */
  _set(
    "networks",
    "all",
    "");
  /* global
       rpc_selection:
         writable */
  _set(
    "rpc",
    "selection",
    "");
  /* global
       key_fingerprint:
         writable */
  _set(
    "key",
    "fingerprint",
    "");
  /* global
       explorer_selection:
         writable */
  _set(
    "explorer",
    "selection",
    "");
  /* global
       retries_max:
         writable */
  _set(
    "retries",
    "max",
    "");
  /* global
       call_timeout:
         writable */
  _set(
    "call",
    "timeout",
    "");
  /* global
       measure_unit:
         writable */
  _set(
    "measure",
    "unit",
    "");
  /* global
       balance_lifespan:
         writable */
  _set(
    "balance",
    "lifespan",
    "");
  /* global
       qr_support:
         writable */
  _set(
    "qr",
    "support",
    "");
  const
    _global =
      _global_get();
  /* global
       quiet:
         writable */
  _global[
    "quiet"] =
    "";
  /* global
       verbose:
         writable */
  _global[
    "verbose"] =
    "";
}

function
  _tasks_parallel_auto_detect() {
  if ( networks_all == "y" ) {
    tasks_parallel =
      10;
  }
  else if ( networks_all == "n" ) {
    tasks_parallel =
      1;
  }
  else {
    const
      _msg =
        `Invalid value '${tasks_parallel}' ` +
        `for variable '${tasks_parallel}'`;
    _msg_error(
      _msg,
      1);
  }
}

function
  _call_timeout_auto_detect() {
  if ( typeof(
         call_timeout) == "undefined" ||
       call_timeout == "" ) {
    if ( target_command == "get" ) {
      call_timeout =
        "30000";
    }
    else {
      call_timeout =
        "300000";
    }
  }
}

function
  _target_key_auto_detect() {
  if ( typeof(
         target_key) == "undefined" ||
       target_key == "" ) {
    if ( target_command == "get" ) {
      target_key =
        "name";
    }
  }
}

function
  _key_fingerprint_auto_detect() {
  if ( wallet_name != "" ) {
    // TODO:
    //   implement EVM GNUPG in Javascript
    true;
  }
}

function
  _output_type_check() {
  let
    _flag,
    _type;
  _flag =
    "false";
  const
    _output_types = [
      "",
      "name",
      "address",
      "fingerprint"
    ];
  for ( _type of _output_types ) {
    if ( output_type == _type ) {
      _flag =
        "true";
      break;
    }
  }
  if ( _flag == "false" ) {
    const
      _msg =
        `Invalid output type '${output_type}'.`;
    _msg_error(
      _msg,
      1);
  }
}

async function 
  _overrides_set() {
  if ( call_date == "" ) {
    call_date =
      _get_date_human();
  }
  if ( typeof(
         wallet_name) == "undefined" ||
       wallet_name == "" ) {
    wallet_name =
      "default";
  }
  if ( typeof(
         target_command) == "undefined" ||
       target_command == "" ) {
    target_command =
      "get";
  }
  if ( networks_all == "" ) {
    networks_all =
      "n";
  }
  _tasks_parallel_auto_detect();
  _call_timeout_auto_detect();
  if ( config_dir == "" ) {
    const
      _home =
        _homedir_get();
    config_dir =
      `${_home}/.config/evm-wallet`;
  }
  if ( cache_dir == "" ) {
    cache_dir =
      `${_homedir_get()}/.cache/evm-wallet`;
  }
  _target_key_auto_detect();
  if ( balance_lifespan == "" ) {
    balance_lifespan =
      "3600";
  }
  if ( typeof(
         retries_max) == "undefined" ||
       retries_max == "" ) {
    retries_max =
      "2";
  }
  if ( typeof(
         measure_unit) == "undefined" ||
       measure_unit == "" ) {
    measure_unit =
      "ether";
  }
  if ( currency_type == "" ) {
    if ( currency_address == "" ) {
      currency_type =
        "gas";
    }
    else if ( currency_address != "" ) {
      currency_type =
        "erc20";
    }
  }
  if ( rpc_selection == "" ) {
    // TODO:
    //   remove all references to that
    //   monster
    rpc_selection =
      "kirsh";
  }
  if ( explorer_selection == "" ) {
    // TODO:
    //   remove all references to that
    //   humunculus
    explorer_selection =
      "kirsh";
  }
  // TODO:
  //   explorers api keys, optional frankly
  //   since theres the evm-contracts-source-index
  const
    _wallet_set_up =
      await _wallet_overrides_set(
        "evm-wallet",
        wallet_name,
        "y",
        "n");
  if ( target_networks.length < 1 &&
       networks_all == "n" ) {
    target_networks.push(
      100);
  }
  _key_fingerprint_auto_detect();
  _output_type_check();
  // See https://github.com/openpgpjs/openpgpjs/issues/2004
  if ( qr_support == "" ) {
    qr_support =
      "n";
  }
  return true;
}

function
  _config_show() {
  /* LibEVM-defined global variables */
  /* global
       api_key */
  /* global
       wallet_address */
  /* global
       wallet_password */
  /* global
       wallet_path */
  /* global
       wallet_seed */
  let
    _line;
  const
    _text = [
      `${app_name} configuration:`,
      `                  Call date:   ${call_date}`,
      `        Runtime environment:   ${runtime_environment}`,
      `             Target command:   ${target_command}`,
      `                Wallet name:   ${wallet_name}`,
      `                 Target key:   ${target_key}`,
      `               Target value:   ${target_value}`,
      `               All networks:   ${networks_all}`,
      `       RPC selection method:   ${rpc_selection}`,
      ` Explorers selection method:   ${explorer_selection}`,
      `               Measure unit:   ${measure_unit}`,
      `           Balance lifespan:   ${balance_lifespan}`,
      `             Send options:`,
      `              Currency type:   ${currency_type}`,
      `           Currency address:   ${currency_address}`,
      `             List options:`,
      `                Output type:   ${output_type}`,
      `      Credentials options:`,
      `                Wallet path:   ${wallet_path}`,
      `                Wallet seed:   ${wallet_seed}`,
      `                    API Key:   ${api_key}`,
      `             Wallet address:   ${wallet_address}`,
      `            Key fingerprint:   ${key_fingerprint}`,
      `  Quantum resistant ciphers:   ${qr_support}`,
      `          Network options:`,
      `            Maximum retries:   ${retries_max}`,
      `               Call timeout:   ${call_timeout}`,
      `             Parallel tasks:   ${tasks_parallel}`,
      `           LibEVM options:`,
      `             Target network:   ${target_networks[0]}`,
      `      Application options:`,
      `    Configuration directory:   ${config_dir}`,
      `            Cache directory:   ${cache_dir}`,
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _text = [
      "EVM networks wallet",
      "",
      "Usage:",
      "",
      "  evm-wallet.js",
      "    [options]",
      "    <command>",
      "      <command-args>",
      "",
      "  commands:",
      "    get",
      "      <wallet-name>",
      "      <key>",
      "    list",
      "    <filter>",
      "    set",
      "      <wallet-name>",
      "      <key>",
      "      <value>",
      "    send",
      "      <address>",
      "      <amount>",
      "",
      "  keys:",
      "    address",
      "    balance",
      "    name",
      "    seed",
      "",
      "  networks:",
      "    all those supported by",
      "    'evm-chains-info' as",
      "    well as direct RPC addresses",
      "",
      "  options:",
      "",
      "     -R --rpc-selection              RPC selection method.",
      `       <rpc-selection>               Default: '${rpc_selection}`,
      "",
      "     -S --explorer-selection         Network explorer selection method.",
      `       <explorer-selection-method>   Default: '${explorer_selection}'`,
      "",
      "     -r --retries-max                Maximum number of retries before",
      "       <retries-max>                 failure.",
      `                                     Default: '${retries_max}'`,
      "",
      "     -u --measure-unit               Measure unit. It can be",
      "       <measure-unit>                'ether' or 'wei'.",
      `                                     Default: '${measure_unit}'`,
      "",
      "     -l --balance-lifespan           Maximum threshold in seconds",
      "       <balance-lifespan>            from now after which to consider",
      "                                     the balance outdated.",
      `                                     Default: '${balance_lifespan}'`,
      "",
      "     -a --networks-all               Operation valid for all available",
      "                                     networks.",
      `                                     Default: '${networks_all}'`,
      "",
      "     -P --tasks-parallel             Tasks to perform in",
      "       <tasks-parallel>              parallel/concurrently.",
      `                                     Default: '${tasks_parallel}'`,
      "",
      "     -Q --qr-support                 Quantum resistance support.",
      `       <y/n>                         Default: '${qr_support}'`,
      "",
      "  list options:",
      "",
      "     -o --output-type                It can be 'name', 'address',",
      "       <output-type>                 'name', 'fingerprint'.",
      `                                     Default: '${output_type}'`,
      "",
      "  send options:",
      "",
      "     -t --currency-type              Currency type.",
      "       <currency-type>               It can be 'gas or 'erc20'.",
      `                                     Default: '${currency_type}'`,
      "",
      "     -C --currency                   Address of the ERC20 token",
      "       <address>                     on the network, if type is 'erc20'.",
      `                                     Default: '${currency_address}'`,
      "",
      "  credentials options:",
      "",
      "     -w --wallet-path                Wallet file path.",
      `       <wallet-path>                 Default: '${wallet_path}'`,
      "",
      "     -p --wallet-password            Wallet password file.",
      `       <wallet-password>             Default: '${wallet_password}'`,
      "",
      "     -s --wallet-seed                Wallet seed file.",
      `       <wallet-seed>                 Default: '${wallet_seed}'`,
      "",
      "     -k --api-key                    Etherscan-like service key.",
      `       <wallet-seed>                 Default: '${api_key}'`,
      "",
      "  libEVM options:",
      "",
      "     -n --network                    EVM network name. Accepted",
      "       <network>                     are all those supported by",
      "                                     'evm-chains-info' and RPC addresses.",
      "",
      "  application options:",
      "",
      "     -K --config-dir                 Configuration directory.",
      `       <config-dir>                  Default: '${config_dir}'`,
      "",
      "     -W --cache-dir                  Cache directory.",
      `       <cache-dir>                   Default: '${cache_dir}'`,
      "",
      "     -h --help                       This message.",
      "     -v --verbose                    Enable verbose output.",
      "",
    ];
  for ( _line of _text ) {
    _echo(
      _line);
  }
  _exit(
    _exit_code);
}

async function 
  _cmdline_parse() {
  let
    _help_display;
  const
    _argv_args = {
      "booleans": [
        "h",
        "help",
        "v",
        "verbose"
      ],
      "string":
        true
    };
  const
    _argv =
      await _argv_get(
        _argv_args);
  const
    _options =
      _argv[
        "_"];
  const
    _global =
      _global_get();
  _global[
    "quiet"] = 
    "y";
  if ( _argv[
         "v"] ||
       _argv[
         "verbose"]) {
    _global[
      "verbose"] =
      true;
  }
  if ( _global[
         "verbose"] ) {
    _global[
      "quiet"] =
      "n";
  }
  _set(
    "runtime",
    "environment",
    "node");
  if ( _argv["h"] == true ) {
    _help_display =
      true;
  }
  if ( _argv["help"] == true ) {
    _help_display =
      true;
  }
  if ( ( _options.indexOf(
           "--help") > -1 ||
         _options.indexOf(
           "-h") > -1) ) {
    _help_display =
      true;
  }
  if ( _help_display ) {
    // _global[
    //   "quiet"] =
    //   "n";
    await _overrides_set();
    _usage(
      0);
  }
  if ( typeof(
       _argv) != "undefined" &&
       0 < _argv[
             "_"].length ) {
    _set(
      "target",
      "command",
      _argv[
        "_"][
          0]);
  }
  const
    _target_command =
      _get(
        "target",
        "command");
  if ( typeof(
       _argv) != "undefined" &&
       1 < _argv[
             "_"].length ) {
    if ( _target_command == "list" ) {
      _set(
        "target",
        "key",
        _argv[
          "_"][
            1]);
    }
    else {
      _set(
        "wallet",
        "name",
        _argv[
          "_"][
            1]);
    }
  }
  if ( typeof(
       _argv) != "undefined" &&
       2 < _argv[
             "_"].length ) {
    if ( _target_command == "list" ) {
      true;
    }
    else if ( _target_command == "send" ) {
      const
        _key =
          _argv._[
            2];
      _set(
        "target",
        "key",
        _argv[
          "_"][
            2].toString());
    }
    else {
      _set(
        "target",
        "key",
        _argv[
          "_"][
            2]);
    }
  }
  if ( typeof(
       _argv) != "undefined" &&
       2 < _argv[
             "_"].length ) {
    _set(
      "target",
      "key",
      _argv[
        "_"][
          2]);
  }
  if ( typeof(
       _argv) != "undefined" &&
       3 < _argv[
             "_"].length ) {
    _set(
      "target",
      "value",
      _argv[
        "_"][
          3]);
  }
  if ( "R" in _argv ) {
    _set(
      "rpc",
      "selection",
      _argv[
        "R"]);
  }
  if ( "rpc-selection" in _argv ) {
    _set(
      "rpc",
      "selection",
      _argv[
        "rpc-selection"]);
  }
  if ( "S" in _argv ) {
    _set(
      "explorer",
      "selection",
      _argv[
        "S"]);
  }
  if ( "explorer-selection" in _argv ) {
    _set(
      "explorer",
      "selection",
      _argv[
        "explorer-selection"]);
  }
  if ( "r" in _argv ) {
    _set(
      "retries",
      "max",
      _argv[
        "r"]);
  }
  if ( "retries-max" in _argv ) {
    _set(
      "retries",
      "max",
      _argv[
        "retries-max"]);
  }
  if ( "u" in _argv ) {
    _set(
      "measure",
      "unit",
      _argv[
        "u"]);
  }
  if ( "measure-unit" in _argv ) {
    _set(
      "measure",
      "unit",
      _argv[
        "measure-unit"]);
  }
  if ( "l" in _argv ) {
    _set(
      "balance",
      "lifespan",
      _argv[
        "l"]);
  }
  if ( "balance-lifespan" in _argv ) {
    _set(
      "balance",
      "lifespan",
      _argv[
        "balance-lifespan"]);
  }
  if ( "a" in _argv ) {
    _set(
      "networks",
      "all",
      "y");
  }
  if ( "networks-all" in _argv ) {
    _set(
      "networks",
      "all",
      "y");
  }
  if ( "P" in _argv ) {
    _set(
      "tasks",
      "parallel",
      _argv[
        "P"]);
  }
  if ( "tasks-parallel" in _argv ) {
    _set(
      "tasks",
      "parallel",
      _argv[
        "tasks-parallel"]);
  }
  if ( "Q" in _argv ) {
    _set(
      "qr",
      "support",
      _argv[
        "Q"]);
  }
  if ( "qr-support" in _argv ) {
    _set(
      "qr",
      "support",
      _argv[
        "qr-support"]);
  }
  if ( "o" in _argv ) {
    _set(
      "output",
      "type",
      _argv[
        "o"]);
  }
  if ( "output-type" in _argv ) {
    _set(
      "output",
      "type",
      _argv[
        "output-type"]);
  }
  if ( "t" in _argv ) {
    _set(
      "currency",
      "type",
      _argv[
        "t"]);
  }
  if ( "currency-type" in _argv ) {
    _set(
      "currency",
      "type",
      _argv[
        "currency-type"]);
  }
  if ( "C" in _argv ) {
    _set(
      "currency",
      "address",
      _argv[
        "C"]);
  }
  if ( "currency" in _argv ) {
    _set(
      "currency",
      "address",
      _argv[
        "currency"]);
  }
  _libevm_cmdline_parse(
    _argv);
}

function
  _url_parse() {
  const
    _argv =
      _argv_url_get();
  _set(
    "runtime",
    "environment",
    "browser");
  _set(
    "wallet",
    "name",
    _argv_url_get(
      "wallet_name")[
        0]);
  _set(
    "rpc",
    "selection",
    _argv_url_get(
      "rpc_selection")[
        0]);
  _set(
    "explorer",
    "selection",
    _argv_url_get(
      "explorer_selection")[
        0]);
  _set(
    "retries",
    "max",
    _argv_url_get(
      "retries_max")[
        0]);
  _set(
    "measure",
    "unit",
    _argv_url_get(
      "measure_unit")[
        0]);
  _set(
    "balance",
    "lifespan",
    _argv_url_get(
      "balance_lifespan")[
        0]);
  _set(
    "networks",
    "all",
    _argv_url_get(
      "networks_all")[
        0]);
  _set(
    "tasks",
    "parallel",
    _argv_url_get(
      "tasks_parallel")[
        0]);
  _set(
    "qr",
    "support",
    _argv_url_get(
      "qr_support")[
        0]);
  _set(
    "output",
    "type",
    _argv_url_get(
      "output_type")[
        0]);
  _set(
    "currency",
    "type",
    _argv_url_get(
      "currency_type")[
        0]);
  _set(
    "currency",
    "address",
    _argv_url_get(
      "currency_address")[
        0]);
  _set(
    "config",
    "dir",
    _argv_url_get(
      "config_dir")[
        0]);
  _set(
    "cache",
    "dir",
    _argv_url_get(
      "cache_dir")[
        0]);
  _libevm_url_parse();
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    _argv_url_get(
      "quiet");
  if ( _global[
         "quiet"].length === 0 ) {
    _global[
      "quiet"] =
      "n";
  }
}

async function
  _main() {
  let
    _msg,
    _result,
    _results;
  const
    _overrides_set_up =
      await _overrides_set();
  const
    _target_network =
      target_networks[
        0];
  const
    _target_network_type =
      typeof(
        _target_network);
  if ( _target_network_type == "object" ) {
    target_networks =
      _target_network;
  }
  _config_show();
  const
    app_opts = [
      target_command,
      wallet_name,
      wallet_path,
      wallet_password,
      wallet_seed,
      key_fingerprint,
      config_dir,
      cache_dir,
      networks_all,
      rpc_selection,
      api_key,
      retries_max,
      tasks_parallel,
      call_timeout,
      measure_unit,
      balance_lifespan,
      currency_type,
      currency_address,
      output_type,
      target_key,
      target_value,
      target_networks
    ];
  _results =
    await _evm_wallet.apply(
      null,
      app_opts);
  const
    _results_type =
      typeof(
        _results);
  if ( _results_type == "number" ) {
    if ( target_command == "blocknumber" ) {
      _results =
        _results.toFixed(
          0);
    }
    console.log(
      _results);
    _exit(
      0);
  }
  else if ( _results_type == "bigint" ) {
    console.log(
      _results.toString());
  }
  else if ( _results_type == "string" ) {
    console.log(
      _results);
  }
  else if ( _results_type == "object" ) {
    if ( target_command == "get" ) {
      if ( target_key == "balance" ) {
        if ( target_networks.length < 2 ) {
          const
            _target_network =
              target_networks[
                  0];
          console.log(
            _results[
              _target_network]);
        }
        else {
          console.log(
            _results);
        }
      }
    }
    else {
      try {
        for ( _result of _results ) {
          console.log(
            _result);
        }
      }
      catch(
        _error) {
        console.error(
          _error);
        _msg =
          "Unknown error.";
        _msg_error(
          _msg,
          1);
      }
    }
  }
  else if ( _results_type == "undefined" ) {
    _msg =
      `No results.`;
    _msg_error(
      _msg,
      1);
  }
  else {
    _msg =
      "Error retrieving results for command. " +
      `Type of return: '${_results_type}'.`;
    _msg_error(
      _msg,
      1);
  }
  _exit(
    0);
}

_global_variables();
_libevm_global_variables();
if ( await _cmdline_check(
       "evm-wallet.js") == true ||
     await _cmdline_check(
       "evm-wallet") == true ) {
  await _cmdline_parse();
}
else {
  _url_parse();
}
_main();
