#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     libevm-wallet
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the
 *     GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* eslint-disable
     no-unused-vars */

/* Crash Javascript global variables */
/* global
     quiet */

const
  _crash_js_module =
    await import(
      "crash-js");
/* global
     _basename */
const
  _basename =
    _crash_js_module._basename;
/* global
     _cat */
const
  _cat =
    _crash_js_module._cat;
/* global
     _file_read */
const
  _file_read =
    _crash_js_module._file_read;
/* global
     _file_exists */
const
  _file_exists =
    _crash_js_module._file_exists;
/* global
     _homedir_get */
const
  _homedir_get =
    _crash_js_module._homedir_get;
/* global
     _ls */
const
  _ls =
    _crash_js_module._ls;
/* global
     _mkdir */
const
  _mkdir =
    _crash_js_module._mkdir;
/* global
     _msg_info */
const
  _msg_info =
    _crash_js_module._msg_info;
/* global
     _msg_error */
const
  _msg_error =
    _crash_js_module._msg_error;
/* global
     _path_join */
const
  _path_join =
    _crash_js_module._path_join;
/* global
     _require */
const
  _require =
    _crash_js_module._require;
/* global
     _stat */
const
  _stat =
    _crash_js_module._stat;
const
  _address_get_module =
    await import(
      "./lib/address-get");
/* global
     _address_get */
const
  _address_get =
    _address_get_module._address_get;
const
  _balance_check_module =
    await import(
      "./lib/balance-check");
/* global
     _balance_check */
const
  _balance_check =
    _balance_check_module._balance_check;
/* global
     _msg_error_balance_insufficient */
const
  _msg_error_balance_insufficient =
    _balance_check_module._msg_error_balance_insufficient;
const
  _balance_get_module =
    await import(
      "./lib/balance-get");
/* global
     _balance_get */
const
  _balance_get =
    _balance_get_module._balance_get;
const
  _balance_send_module =
    await import(
      "./lib/balance-send");
/* global
     _balance_send */
const
  _balance_send =
    _balance_send_module._balance_send;
const
  _block_number_get_module =
    await import(
      "./lib/block-number-get");
/* global
     _block_number_get_get */
const
  _block_number_get =
    _block_number_get_module._block_number_get;
const
  _ethers_to_wei_module =
    await import(
      "./lib/ethers-to-wei");
/* global
     _ethers_to_wei */
const
  _ethers_to_wei =
    _ethers_to_wei_module._ethers_to_wei;
const
  _network_provider_module =
    await import(
      "./lib/network-provider");
/* global
     _msg_info_provider_generated */
const
  _msg_info_provider_generated =
    _network_provider_module._msg_info_provider_generated;
/* global
     _provider_get */
const
  _provider_get =
    _network_provider_module._provider_get;
/* global
     _target_networks_check */
const
  _target_networks_check =
    _network_provider_module._target_networks_check;
const
  _price_gas_get_module =
    await import(
      "./lib/price-gas-get");
/* global
     _price_gas_get */
const
  _price_gas_get =
    _price_gas_get_module._price_gas_get;
const
  _price_gas_transaction_get_module =
    await import(
      "./lib/price-gas-transaction-get");
/* global
     _price_gas_transaction_get */
const
  _price_gas_transaction_get =
    _price_gas_transaction_get_module._price_gas_transaction_get;
const
  _seed_new_module =
    await import(
      "./lib/seed-new");
/* global
     _seed_new */
const
  _seed_new =
    _seed_new_module._seed_new;
const
  _wallet_get_module =
    await import(
      "./lib/wallet-get");
/* global
     _wallet_get */
const
  _wallet_get =
    _wallet_get_module._wallet_get;
const
  _wallet_new_module =
    await import(
      "./lib/wallet-new");
/* global
     _wallet_new */
const
  _wallet_new =
    _wallet_new_module._wallet_new;

async function
  _conf_dir_get() {
  const
    _home =
      _homedir_get();
  const
    _app_name =
      "evm-wallet";
  const
    _msg =
      "Auto-detecting " +
      "config file. Setting " +
      "canonical XDG_CONFIG_DIR " +
      `'${_app_name}'.`;
  const
    _config_dir =
      `${_home}/.config/${_app_name}`;
  return _config_dir;
}

async function
  _balance_update(
    _cache_dir,
    _wallet_name,
    _wallet_seed,
    _target_networks,
    _rpc,
    _api_key,
    _measure_unit,
    _retries_max,
    _balance_lifespan,
    _call_timeout) {
  let
    _balance_dir,
    _balance_file,
    _balance_file_modified,
    _balance_get_args,
    _life,
    _network;
  const
    _balance =
      {};
  for ( _network of _target_networks ) {
    const
      _balance_dir =
        _path_join( [
          _cache_dir,
          _wallet_name,
          _network.toString() ]);
    const
      _balance_file =
        _path_join( [
          _balance_dir,
          "balance"]);
    const
      _balance_get_args = [
        _wallet_seed,
        _rpc[
          _network],
        _api_key,
        "",                  // Target address, using seed
        _measure_unit,
        _balance_file,
        _retries_max,
        _call_timeout
      ];
    if ( ! _file_exists(
             _balance_dir) ) {
      _mkdir(
        _balance_dir,
        { "recursive":
            true });
    }
    if ( ! _file_exists(
             _balance_file) ) {
      _balance[
        _network] =
        await _balance_get.apply(
          null,
          _balance_get_args);
    }
    else {
      const
        _balance_file_modified =
          _stat(
            _balance_file).mtimeMs;
      const
        _life =
          Date.now() -
          _balance_file_modified;
      if ( _balance_lifespan < _life ) {
        _balance[
          _network] =
          await _balance_get.apply(
            null,
            _balance_get_args);
      }
      else {
        _balance[
          _network] =
          _cat(
            _balance_file);
      }
    }
  }
  return _balance;
}

async function
  _wallet_address_get(
    _config_dir,
    _wallet_name,
    _wallet_seed) {
  let
    _address_get_args,
    _error,
    _msg,
    _wallet_address,
    _wallet_address_get_args;
  if ( _config_dir == "" ||
       typeof(_config_dir) === "undefined" ) {
    _config_dir =
      _conf_dir_get();
  }
  if ( _wallet_name == "" ||
       typeof(
         _wallet_name) === "undefined" ) {
    if ( _wallet_seed == "" ||
       typeof(
         _wallet_seed) == "undefined" ) {
      _msg =
        "Either one between the wallet name " +
        "or the wallet seed argument must be non-empty. " +
        "_wallet_address_get(_config_path, " +
        "_wallet_name, _wallet_seed)";
      _error = {
        "message":
          _msg
      };
      throw _error;
    }
    const
      _address_get_args = [
        _wallet_seed,
        "",                       // Network
        "",                       // API Key
        "",                       // Chain ID
        "",                       // Chain name
        ""                        // Output file
      ];
    _wallet_address =
      await _address_get.apply(
        null,
        _address_get_args);
  }
  else if ( _wallet_name != "" ) {
    const
      _wallet_address_path =
        `${_config_dir}/${_wallet_name}-address.txt`;
    if ( _file_exists(
           _wallet_address_path) ) {
      _wallet_address =
        _file_read(
          _wallet_address_path);
    }
    else {
      if ( _file_exists(
             _wallet_seed) ) {
        const
          _address_get_args = [
            _wallet_seed,
            "",                   // Network
            "",                   // API Key
            "",                   // Chain ID
            "",                   // Chain name
            _wallet_address_path  // Output file
          ];
        _wallet_address =
          await _address_get.apply(
            null,
            _address_get_args);
      }
      else {
        _msg =
          "Found no recorded address nor seed for " +
          `name '${_wallet_name}' in '${_config_dir}'.`;
        _error = {
          "message":
            _msg
        };
        throw _error;
      }
    }
  }
  else {
    _msg =
      "Argument 'wallet name' must " +
      "be of type 'string'.";
    _error = {
      "message":
        _msg
    };
    throw _error;
  }
  return _wallet_address;
}

async function
  _wallets_files_get(
    _config_dir,
    _filter) {
  let
    _regexp,
    _wallet,
    _wallet_name,
    _wallet_path;
  const
    _wallets_files =
     [];
  const
    _wallets =
      await _ls(
        _config_dir);
  const
    _data_types = [
      "address",
      "fingerprint",
      "seed"
    ];
  for ( _wallet of _wallets ) {
    for ( _data_type of _data_types ) {
      if ( _wallet.endsWith(
             `-${_data_type}.txt`) ) {
        _regexp =
          RegExp(
            `-${_data_type}.txt$`);
        _wallet_name =
          _wallet.replace(
            _regexp,
            "");
        if ( _wallet_name.includes(
               `${_filter}`) ) {
          _wallet_path =
            _path_join([
              _config_dir,
              _wallet
            ]);;
          _wallet_files.push(
            _wallet_path);
        }
      }
    }
  }
  return _wallet_paths;
}

function
  _wallets_sort(
    _wallet_files) {
  return _wallet_files;
  }

async function
  _contacts_list(
    _filter,
    _output_type,
    _config_dir) {
  let
    _regexp,
    _wallets_files;
  const
    _addresses =
      {};
  const
    _fingerprints =
      {};
  const
    _wallets =
      {};
  if ( _filter == "" ) {
    _filter =
      "*";
  }
  _wallets_files =
    await _wallets_files_get(
      _config_dir,
      _filter);
  _wallets_files =
    _wallet_sort(
      _wallet_files);
  for ( _wallet of _wallet_files ) {
    _file_name =
      _basename(
        _wallet);
    if ( _file_name.endsWith(
           "-seed.txt") ) {
      _regexp =
        RegExp(
          "-seed.txt$");
      _wallet_name =
        _file_name.replace(
          _regexp,
          "");
      _wallet_path =
        _path_join([
          _config_dir,
          _file_name
        ];
      _wallets[
        _wallet_name] =
        _wallet_path;
    }
    else if ( _file_name.endsWith(
                "-address.txt") ) {
      _regexp =
        RegExp(
          "-address.txt$");
      _wallet_name =
        _file_name.replace(
          _regexp,
          "");
      _addresses[
        _wallet_name] =
        _cat(
          _wallet);
      if ( _output_type == "" ||
           _output_type == "fingerprint" ) {
        _msg =
          "Getting fingerprint for"
          `contact '${_wallet_name}'.`;
        _msg_info(
          _msg);
        const
          _fingerprint =
            await _fingerprint_get(
              _wallet_name);
      }
    }
  }
}

async function
  _transfer(
    _target_address,
    _target_amount,
    _target_network,
    _currenty_type,
    _retries_max,
    _call_timeout,
    _wallet_seed,
    _api_key,
    _rpc,
    _currency_address,
    _measure_unit) {
  if ( _currency_type == "gas" ) {
    const
      _balance_send_args = [
        _wallet_seed,
        _target_address,
        _target_amount,
        _rpc[
          _target_network],
        _api_key,
        _measure_unit
      ];
    const
      [ _tx,
        _receipt ] =
        await _balance_send.apply(
          null,
          _balance_send_args);
    return [ _tx,
             _receipt ];
  }
  else if ( _currency_type == "erc20" ) {
    try {
      const
        _erc20_tools_module =
          await _require(
            "erc20-tools");
      const
        _token_send =
          _erc20_tools_module._token_send;
      const
        _token_send_args = [
          _retries_max,
          _call_timeout,
          _wallet_seed,
          _api_key,
          _rpc,                          // NOTE: data filled-in
          _currency_address,             // by 'token-send':
          "",                            //   erc20 abi
          "",                            //   erc20 bytecode
          "",                            //   erc20 hardhat artifact
          _measure_unit,
          "",                            // output path
          _target_address,
          _target_amount
        ];
      _msg =
        `Running '_token_send' with ` +
        `arguments '${_token_send_args}'.`;
      _msg_info(
        _msg);
      const
        _token_sent =
          await _token_send.apply(
            null,
            _token_send_args);
      return _token_sent;
    }
    catch(
      _error) {
      _msg =
        "Install ERC-20 Tools ('ur erc20-tools')";
      const
        _exception = {
          "msg":
            _msg
        };
      _msg_error(
        _msg,
        0);
      throw _exception;
    }
  }
  else {
    _msg =
      `Unknown currency type '${_currency_type}'.`;
    _msg_error(
      _msg,
      1);
  }
}

async function
  _evm_wallet(
    _target_command,
    _wallet_name,
    _wallet_path,
    _wallet_password,
    _wallet_seed,
    _key_fingerprint,
    _config_dir,
    _cache_dir,
    _networks_all,
    _rpc_selection,
    _api_key,
    _retries_max,
    _tasks_parallel,
    _call_timeout,
    _measure_unit,
    _balance_lifespan,
    _currency_type,
    _currency_address,
    _output_type,
    _target_key,
    _target_value,
    _target_networks) {
  let
    _msg,
    _network,
    _target_network,
    _tx,
    _receipt;
  const
    _libevm_module =
      await _require(
        "libevm");
  const
    _rpc_get =
      _libevm_module._rpc_get;
  [ _target_networks,
    _target_network ] =
    _target_networks_check(
      _target_networks);
  const
    _rpc =
      _rpc_get(
        _target_networks);
  _msg =
    `Using RPC address:`;
  _msg_info(
    _msg);
  if ( quiet == "n" ) {
    console.log(
      _rpc);
  }
  if ( _target_command == "blocknumber" ) {
    const
      _block_number_get_args = [
        _rpc[
          _target_network],
        _api_key,
        "",            // output file
        _retries_max,
        _call_timeout,
      ];
    const
      _block_number =
        await _block_number_get.apply(
          null,
          _block_number_get_args);
    return _block_number;
  }
  else if ( _target_command == "gas" ) {
    const
      _price_gas_get_args = [
        _rpc[
          _target_network],
        _api_key,
        _measure_unit,
        "",            // seed
        "",            // target address
        "",            // output file
        _retries_max
      ];
    const
      _price_gas =
        await _price_gas_get.apply(
          null,
          _price_gas_get_args);
    return _price_gas;
  }
  else if ( _target_command == "get" ) {
    if ( _target_key == "balance" ) {
      const
        _balance_update_args = [
          _cache_dir,
          _wallet_name,
          _wallet_seed,
          _target_networks,
          _rpc,
          _api_key,
          _measure_unit,
          _retries_max,
          _balance_lifespan,
          _call_timeout
        ];
      const
        _balance =
          await _balance_update.apply(
            null,
            _balance_update_args);
      return _balance;
    }
    else if ( _target_key == "address" ) {
      const
        _wallet_address_get_args = [
          _config_dir,
          _wallet_name,
          _wallet_seed,
        ];
      const
        _wallet_address =
          await _wallet_address_get.apply(
            null,
            _wallet_address_get_args);
      return _wallet_address;
    }
    else {
      _msg =
        `Unknown key '${_target_key}'.`;
      _msg_error(
        _msg,
        1);
    }
  }
  else if ( _target_command == "send" ) {
    const
      _target_address =
        _target_key;
    const
      _target_amount =
        _target_value;
    const
      _transfer_args = [
        _target_address,
        _target_amount,
        _target_network,
        _currenty_type,
        _retries_max,
        _call_timeout,
        _wallet_seed,
        _api_key,
        _rpc,
        _currency_address,
        _measure_unit) {
      ];
    const
      [ _tx,
        _receipt ] =
        await _transfer.apply(
          null,
          _transfer_args);
      return [
        _tx,
        _receipt ];
    }
  }
  else if ( _target_command == "list" ) {
    const
      _filter =
        _target_key;
    const
      _contacts_list_args = [
        _filter,
        _output_type
      ];
    const
      _contacts =
        await _contacts_list.apply(
          null,
          _contacts_list_args);
    return _contacts;
  }
  else if ( _target_command == "run" ) {
    true;
  }
  else {
    _msg =
      `Unknown command '${_target_command}'.`;
    _msg_error(
      _msg,
      0);
    const
      _exception =
        "msg":
          _msg
      };
    throw _msg;
  }
}

// ES6 module exports

export {
    _address_get,
    _balance_check,
    _msg_error_balance_insufficient,
    _balance_get,
    _balance_send,
    _block_number_get,
    _conf_dir_get,
    _evm_wallet,
    _ethers_to_wei,
    _provider_get,
    _msg_info_provider_generated,
    _price_gas_get,
    _price_gas_transaction_get,
    _transfer,
    _seed_new,
    _wallet_address_get,
    _wallet_get,
    _wallet_new
};

// Common Javascript exports

// module.exports = {
//   _address_get:
//     _address_get,
//   _balance_check:
//     _balance_check,
//   _msg_error_balance_insufficient:
//     _msg_error_balance_insufficient,
//   _balance_get:
//     _balance_get,
//   _balance_send:
//     _balance_send,
//   _block_number_get:
//     _block_number_get,
//   _conf_dir_get:
//     _conf_dir_get,
//   _evm_wallet:
//     _evm_wallet,
//   _ethers_to_wei:
//     _ethers_to_wei,
//   _provider_get:
//     _provider_get,
//   _msg_info_provider_generated:
//     _msg_info_provider_generated,
//   _price_gas_get:
//     _price_gas_get,
//   _price_gas_transaction_get:
//     _price_gas_transaction_get,
//   _transfer:
//     _transfer,
//   _seed_new:
//     _seed_new,
//   _wallet_address_get:
//     _wallet_address_get,
//   _wallet_get:
//     _wallet_get,
//   _wallet_new:
//     _wallet_new
// };
