#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    require(
      "crash-js");
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _basename */
const
  _basename =
    _libcrash._basename;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _dirname */
const
  _dirname =
    _libcrash._dirname;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _file_read */
const
  _file_read =
    _libcrash._file_read;
/* global
     _file_write */
const
  _file_write =
    _libcrash._file_write;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_info_obj */
const
  _msg_info_obj =
    _libcrash._msg_info_obj;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
     _path_join */
const
  _path_join =
    _libcrash._path_join;
const
  _wallet_get_module =
    require(
      './wallet-get');
/* global
     _wallet_get */
const
  _wallet_get =
    _wallet_get_module._wallet_get;
const
  _network_provider =
    require(
      './network-provider');
/* global
     _provider_get */
const
  _provider_get =
    _network_provider._provider_get;
/* global
     _msg_info_provider_generated */
const
  _msg_info_provider_generated =
    _network_provider._msg_info_provider_generated;

function
  _global_variables() {
  app_name =
    "address-get";
  wallet_seed =
    "";
  target_network =
    "";
  api_key_path =
    "";
  chain_id =
    "";
  chain_name =
    "";
  output_file =
    "";
  quiet =
    "";
}

async function
  _address_get(
    _wallet_seed,
    _target_network,
    _api_key_path,
    _chain_id,
    _chain_name,
    _output_file) {
  let
    _address,
    _api_key,
    _provider_get_opts,
    _wallet_dir,
    _wallet_password,
    _wallet_path_list;
  if ( typeof(
         _wallet_seed) == "undefined" ||
       _wallet_seed == "" ||
       _wallet_seed == [] ) {
    _msg =
      "No input seed file or phrase.";
    _msg_error(
      _msg,
      1);
  }
  _wallet_password =
    "";
  _wallet_dir =
    _dirname(
      _wallet_seed);
  _wallet_path_list = [
    _wallet_dir,
    "wallet.dat"
  ];
  _wallet_path =
    _path_join(
      _wallet_path_list);
  _api_key =
    "";
  if ( _api_key_path != "" ) {
    _api_key =
      _file_read(
        _api_key_path);
  }
  _provider_get_opts = [
    _target_network,
    _api_key,
    _chain_id,
    _chain_name
  ];
  _provider =
    _provider_get.apply(
      null,
      _provider_get_opts);
  _msg_info_provider_generated(
    _provider);
  _wallet_get_opts = [
    _wallet_path,
    _wallet_password,
    _wallet_seed,
    _provider
  ];
  _wallet =
    _wallet_get.apply(
      null,
      _wallet_get_opts);
  _address =
    _wallet.address;
  if ( _output_file != undefined &&
       _output_file != "" ) {
    _file_write(
      _output_file,
      _address);
  }
  return _address;
}

function
  _config_show() {
  let
    _line,
    _text;
  _text = [
    `  ${app_name} configuration:`,
    `      Wallet seed: ${wallet_seed}`,
    `   Target network: ${target_network}`,
    `          API key: ${api_key_path}`,
    `      Output file: ${output_file}`,
  ]
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  if ( typeof(
         _exit_code) == "undefined" ||
       _exit_code == "" ) {
    _exit_code =
      0;
  }
  const
    _argv =
      _argv_get();
  const
    _program =
      _basename(
        _argv[
          "$0"]);
  const
    _text = [
      "Returns the EOA fingerprint of a seed (the address)",
      "",
      "usage:",
      `  ${_program}`,
      "    <quiet>",
      "    <seed>",
      "    (<target-network>)",
      "    (<api-key-path>)",
      "    (<output-file>)",
      "",
      "args:",
      "",
      "  quiet              It can be 'y' or 'n'.",
      "",
      "  seed               A seed path or a seed phrase",
      "",
      "  target-network     Chain ID or RPC address, optional.",
      "",
      "  api-key-path       Etherscan-like service API key, optional.",
      "",
      "  output-file        If specified will save the output",
      "                     to a file, otherwise will print it.",
      "",
      "options:",
      "",
      "  -h, --help         Displays this help.",
      ""
    ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  _exit(
    _exit_code);
}


function _cmdline_parse() {
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        wallet_seed =
          _value;
      }
      if ( _index == 4 ) {
        target_network =
          _value;
      }
      if ( _index == 5 ) {
        api_key_path =
          _value;
      }
      if ( _index == 6 ) {
        output_file =
          _value;
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        _overrides_set();
        quiet =
          "n";
        _usage(
          0);
      }
  });
  if ( wallet_seed == "" ) {
    _overrides_set();
    quiet =
      "n";
    _msg_error(
      "No arguments given.",
      0);
    _usage(
      1);
  }
}

function
  _overrides_set() {
  // _override_set(
  //   "target",
  //   "network",
  //   "127.0.0.1");
  _override_set(
    "chain",
    "id",
    "100");
}

async function 
  _address_get_cmdline(
    _app_opts) {
  const
    _address =
      await _address_get.apply(
        null,
        _app_opts);
  console.log(
    _address);
}

if ( _cmdline_check(
       "address-get") ||
     _cmdline_check(
       "eoa-fingerprint") ) {
  _global_variables();
  _cmdline_parse();
  _overrides_set();
  _config_show();
  app_opts = [
    wallet_seed,
    target_network,
    api_key_path,
    chain_id,
    chain_name,
    output_file
  ];
  _address_get_cmdline(
    app_opts);
}

module.exports = {
  _address_get:
    _address_get
};
