#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _argv */
const
  _argv =
    _libcrash._argv;
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _basename */
const
  _basename =
    _libcrash._basename;
/* global
     dirname */
const
  _dirname =
    _libcrash._dirname;
/* global
     _echo */
const
  _echo =
    _libcrash._echo;
/* global
     _echo2 */
const
  _echo2 =
    _libcrash._echo2;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _file_read */
const
  _file_read =
    _libcrash._file_read;
/* global
     _file_write */
const
  _file_write =
    _libcrash._file_write;
/* global
     _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_info_obj */
const
  _msg_info_obj =
    _libcrash._msg_info_obj;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _path_join */
const
  _path_join =
    _libcrash._path_join;
/* global
     _require */
const
  _require =
    _libcrash._require;
/* global
     _run */
const
  _run =
    _libcrash._run;
/* global
     _sleep */
const
  _sleep =
    _libcrash._sleep;
const
  _ethers_module =
    await _require(
      "ethers");
/* global
     _ethers */
const
  _ethers =
    _ethers_module.ethers;
/* global
     _wei_to_ether */
const
  _wei_to_ether =
    _ethers.formatEther;
const
  _wallet_get_module =
    await import(
      './wallet-get');
/* global
     _wallet_get */
const
  _wallet_get =
    _wallet_get_module._wallet_get;
const
  _network_provider_module =
    await import(
      './network-provider');
/* global
     _provider_get */
const
  _provider_get =
    _network_provider_module._provider_get;
/* global
     _msg_info_provider_generated */
const
  _msg_info_provider_generated =
    _network_provider_module._msg_info_provider_generated;

function
  _global_variables() {
  app_name =
    "balance-get";
  /* global
       wallet_seed:
         writable */
  wallet_seed =
    "";
  /* global
       target_network:
         writable */
  target_network =
    "";
  /* global
       api_key:
         writable */
  api_key =
    "";
  /* global
       target_address:
         writable */
  target_address =
    "";
  /* global
       display_unit:
         writable */
  display_unit =
    "";
  /* global
       output_file:
         writable */
  output_file =
    "";
  /* global
       retries_max:
         writable */
  retries_max =
    "";
  /* global
       quiet:
         writable */
  quiet =
    "";
}


async function
  _balance_get(
    _wallet_seed,
    _target_network,
    _api_key_path,
    _target_address,
    _display_unit,
    _output_file,
    _retries_max,
    _call_timeout) {
  let
    _balance,
    _balance_ether,
    _balance_wei,
    _msg,
    _provider_get_opts,
    _retry,
    _request,
    _success,
    _time_over,
    _wallet_dir,
    _wallet_password,
    _wallet_path_list;
  if ( typeof(
         _retries_max) == 'undefined' ||
       _retries_max == "" ) {
    _retries_max =
      3;
  }
  else {
    _retries_max =
      Number(
        _retries_max);
  }
  if ( typeof(
         _call_timeout) == 'undefined' ||
       _call_timeout == "" ) {
    _call_timeout =
      100000;
  }
  _retry =
    0;
  _success =
    false;
  _wallet_password =
    "";
  if ( _wallet_seed != "" ) {
    _wallet_dir =
      _dirname(
        _wallet_seed);
    _wallet_path_list = [
      _wallet_dir,
      "wallet.dat"
    ];
    _wallet_path =
      _path_join(
        _wallet_path_list);
  }
  _provider_get_opts = [
    _target_network,
  ];
  if ( _output_file == undefined ) {
    _output_file =
      "";
  }
  if ( _api_key_path != "" ) {
    _api_key =
      _file_read(
        _api_key_path);
    _provider_get_opts.push(
      _api_key);
  }
  _provider_get_opts.push(
    _call_timeout);
  _provider =
    await _provider_get.apply(
      null,
      _provider_get_opts);
  _msg_info_provider_generated(
    _provider);
  if ( _target_address == "" ) {
    _wallet_get_opts = [
      _wallet_path,
      _wallet_password,
      _wallet_seed,
      _provider
    ];
    _wallet =
      _wallet_get.apply(
        null,
        _wallet_get_opts);
    _target_address =
      _wallet.address;
  }
  _msg =
    `Retrieving balance for ` +
    `address '${_target_address}' on ` +
    `network '${_target_network}'.`;
  _msg_info(
    _msg);
  while ( _success == false &&
          _retry < _retries_max ) {
    try {
      const
        _provider_get_balance_cmd = [
          _provider,
          _target_address
        ];
      _balance_wei =
        await _run(
          "sync",
          _provider_get_balance_cmd,
          "_provider_get_balance",
          _call_timeout,
          "native",
	  "getBalance");
      if ( _display_unit == "" ) {
        _display_unit =
          "ether";
      }
      if ( _display_unit == "wei" ) {
        _balance =
          _balance_wei;
      }
      else if ( _display_unit == "ether" ) {
        _balance_ether =
          _wei_to_ether(
            _balance_wei);
        _balance =
          _balance_ether;
      }
      if ( _output_file != "" ) {
          _file_write(
            _output_file,
            _balance.toString());
      }
      _success =
        true;
    } catch(
        _err) {
      _retry =
        _retry + 1;
      _msg =
        `Error retrieving balance, ` +
        `retrying (${_retry} of ${_retries_max})`;
      _echo2(
        _err);
      _msg_error(
        _msg,
        0);
      await _sleep(
        3000);
    }
  }
  if ( _success == false &&
       _retry == _retries_max ) {
    _msg =
      "Error retrieving balance.";
    throw _msg;
    return _balance;
  }
  return _balance;
}

async function
  _overrides_set() {
  let
    _info_get,
    _target_network_type;
  _info_get =
    false;
  _target_network_type =
    typeof(
      target_network);
  if ( _target_network_type == "undefined" ||
       target_network == "" ) {
    target_network = 100;
    _target_network_type =
      typeof(
        target_network);
  }
  if ( _target_network_type == "number" ) {
    _info_get =
      true;
  }
  else if ( _target_network_type == "string" ) {
    if ( ! target_network.startsWith(
           "https://") ) {
      _info_get =
        true;
    }
  }
  else {
    const
      _msg =
        `Unknown type '${_target_network_type}' ` +
        `for network variable.`;
    _msg_error(
      _msg,
      1);
  }
  if ( _info_get ) {
    const
      _libevm_module =
        await _require(
          "libevm");
    const
      _rpc_get =
        _libevm_module._rpc_get;
    target_network =
      _rpc_get(
        [ target_network ])[
        target_network];
  }
  _override_set(
    "display",
    "unit",
    "ether");
  _override_set(
    "retries",
    "max",
    "1");
  _override_set(
    "call",
    "timeout",
    "30000");
}

function
  _config_show() {
  let
    _line;
  const
    _program =
      _basename(
        _argv[
          "1"]);
  const
    _text = [
      `  ${_program} configuration:`,
      `      Wallet seed: ${wallet_seed}`,
      `   Target network: ${target_network}`,
      `          API Key: ${api_key}`,
      `   Target address: ${target_address}`,
      `     Display unit: ${display_unit}`,
      `      Output file: ${output_file}`,
      `  Maximum retries: ${retries_max}`
      `     Call timeout: ${call_timeout}`
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  if ( typeof(
         _exit_code) == "undefined" ||
       _exit_code == "" ) {
    _exit_code =
      0;
  }
  const
    _program =
      _basename(
        _argv[
          "1"]);
  const
    _text = [
      "Usage:",
      `  ${_program}`,
      "    <quiet>",
      "    <seed-path>",
      "    <target-network>",
      "  ( <api-keys-path",
      "    <target-address>",
      "    <display-unit>",
      "    <output-file>",
      "    <retries-max>",
      "    <call-timeout> )",
      "",
      "Arguments:",
      "",
      "  <seed-path>         Path on disk of the file",
      "                      containing the seed phrase.",
      "",
      "  <target-network>    Name, chain ID or RPC address",
      "                      of the network to connect to.",
      "",
      "Optional arguments:",
      "",
      "  <api-key-path>      Path on disk of the API key for",
      "                      the network service provider.",
      "",
      "  <target-address>    Address of which to return",
      "                      the balance of.",
      "                      Default: the wallet address.",
      "                      corresponding to the seed.",
      "",
      "  <display-unit>      Can be 'wei' or 'ether'.",
      `                      Default: '${display_unit}'`,
      "",
      "  <output-file>       File in which to save the balance.",
      `                      Default: '${output_file}'`,
      "",
      "  <retries-max>       Maximum number of retries.",
      `                      Default: ${retries_max}`,
      "",
      "  <call-timeout>      Timeout before declaring the call failed.",
      `                      Default: ${call_timeout}`,
  ];
  for ( _line of _text ) {
    _echo(
      _line);
  }
  _exit(
    _exit_code);
}


async function
  _cmdline_parse() {
  let
    _help_display,
    _msg;
  quiet =
    "y";
  _argv.forEach(
    async function (
      _value,
      _index) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        wallet_seed =
          _value;
      }
      if ( _index == 4 ) {
        target_network =
          _value;
      }
      if ( _index == 5 ) {
        api_key =
          _value;
      }
      if ( _index == 6 ) {
        target_address =
          _value;
      }
      if ( _index == 7 ) {
        display_unit =
          _value;
      }
      if ( _index == 8 ) {
        output_file =
          _value;
      }
      if ( _index == 9 ) {
        retries_max =
          _value;
      }
      if ( _index == 10 ) {
        call_timeout =
          _value;
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        _help_display =
          true;
      }
  });
  if ( _help_display ) {
    await _overrides_set();
    quiet =
      "n";
    _usage(
      0);
  }
  if ( wallet_seed == "" &&
       target_address == "" ) {
    _msg =
      "You need to input either " +
      "a seed file path or a target " +
      "address."
    _msg_error(
      _msg,
      0);
    await _overrides_set();
    _usage(
      1);
  }
}

async function
  _balance_get_cmdline(
    _app_opts) {
  try {
    const
      _balance =
        await _balance_get.apply(
          null,
          _app_opts);
    const
      _balance_string =
        _balance.toString();
    _echo(
      _balance_string);
    _exit(
      0);
  }
  catch(
    _error) {
    _msg_error(
      _error,
      1);
    _exit(
      0);
  }
}

async function
  _main() {
  _global_variables();
  await _cmdline_parse();
  await _overrides_set();
  await _config_show();
  app_opts = [
    wallet_seed,
    target_network,
    api_key,
    target_address,
    display_unit,
    output_file,
    retries_max,
    call_timeout
  ];
  await balance_get_cmdline(
    app_opts);
}

if ( await _cmdline_check(
       "balance-get") ||
     await _cmdline_check(
       "gas-balance") ) {
  _main();
}

// ES6 module exports

export {
  _balance_get
};

// Common Javascript exports

// module.exports = {
//   _balance_get:
//     _balance_get
// };
