#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later


/**    ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    require(
      "crash-js");
/* global
     _dirname:
       writable */
const
  _dirname =
    _libcrash._dirname;
/* global
     _exit:
       writable */
const
  _exit =
    _libcrash._exit;
/* global
     _file_read:
       writable */
const
  _file_read =
    _libcrash._file_read;
/* global
     _path_join:
       writable */
const
  _path_join =
    _libcrash._path_join;
/* global
     _msg_info:
       writable */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_info_obj:
       writable */
const
  _msg_info_obj =
    _libcrash._msg_info_obj;
/* global
     _msg_error:
       writable */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _require:
       writable */
const
  _require =
    _libcrash._require;
/* global
     _sleep:
       writable */
const
  _sleep =
    _libcrash._sleep;
const
  { ethers } =
    _require(
      "ethers");
const
  _ethers =
    ethers;
/* global
     _parse_units:
       writable */
const
  _parse_units =
    _ethers.parseUnits;
const
  _wallet_get_module =
    require(
      './wallet-get');
/* global
     _wallet_get:
       writable */
const
  _wallet_get =
    _wallet_get_module._wallet_get;
const
  _balance_get_module =
    require(
      './balance-get');
/* global
     _balance_get:
       writable */
const
  _balance_get =
    _balance_get_module._balance_get;
const
  _network_provider_module =
    require(
      './network-provider');
/* global
     _provider_get:
       writable */
const
  _provider_get =
    _network_provider_module._provider_get;
/* global
     _msg_info_provider_generated:
       writable */
const
  _msg_info_provider_generated =
    _network_provider_module._msg_info_provider_generated;


function
  _global_variables() {
  app_name =
    "balance-check";
  wallet_seed =
    "";
  target_address =
    "";
  target_amount =
    "";
  target_network =
    "";
  api_key =
    "";
  measure_unit =
    "";
  retries_max =
    "";
  quiet =
    "";
}

function
  _msg_error_balance_insufficient(
    _amount,
    _unit) {
  let
    _msg;
  _msg =
    `Amount $'{_amount}' ` +
    `'${_unit}' requested to send ` +
    `is less than balance.`;
  _msg_error(
    _msg,
    1)
}

function
  _ethers_to_wei(
    _amount) {
  return _parse_units(
    _amount,
    "ether");
}

async function
  _balance_check(
    _wallet_seed,
    _target_amount,
    _target_network,
    _api_key_path,
    _measure_unit,
    _retries_max) {
  let
    _amount,
    _api_key,
    _balance,
    _msg,
    _provider_get_opts,
    _retry,
    _sender_address,
    _success,
    _tx,
    _wallet_dir,
    _wallet_password,
    _wallet_path_list;
  if ( typeof(
         _retries_max) == 'undefined' ||
       _retries_max == "" ) {
    _retries_max =
      3;
  }
  else {
    _retries_max =
      Number(
        _retries_max);
  }
  _target_amount =
    Number(
      _target_amount);
  _retry =
    0;
  _success =
    false;
  _wallet_password =
    "";
  _wallet_dir =
    _dirname(
      _wallet_seed);
  _wallet_path_list = [
    _wallet_dir,
    "wallet.dat"
  ];
  _wallet_path =
    _path_join(
      _wallet_path_list);
  _provider_get_opts = [
    _target_network
  ];
  if ( _api_key_path != "" ) {
    _api_key =
      _file_read(
        _api_key_path);
    _provider_get_opts.push(
      _api_key);
  }
  _provider =
    await _provider_get.apply(
      null,
      _provider_get_opts);
  _msg_info_provider_generated(
    _provider);
  _wallet_get_opts = [
    _wallet_path,
    _wallet_password,
    _wallet_seed,
    _provider
  ];
  _wallet =
    _wallet_get.apply(
      null,
      _wallet_get_opts);
  _sender_address =
    _wallet.address;
  if ( _measure_unit == "" ) {
    _measure_unit =
      "ether";
  }
  _balance_get_opts = [
    _wallet_seed,
    _target_network,
    _api_key_path,
    _sender_address,
    _measure_unit
  ];
  while ( _success == false &&
          _retry < _retries_max ) {
    try {
      _balance =
        await _balance_get.apply(
          null,
          _balance_get_opts);
      _balance =
        Number(
          _balance);
      _success =
        true;
      if ( _balance <= _target_amount ) {
        _msg =
          `Balance is '${_balance}', ` +
          `requiring '${_target_amount}'.`;
        _msg_error(
          _msg,
          0);
        return false;
      }
      else if ( _balance > _target_amount ) {
        return true;
      }
    } catch(
        _error) {
      _retry =
        _retry + 1;
      _msg =
        `Error checking balance, ` +
        `retrying (${_retry} of ${_retries_max})`;
      console.error(
        _error);
      _msg_error(
        _msg,
        0);
    }
  }
  if ( _retry == _retries_max &&
       _success == false ) {
    throw "Failing checking the balance."
  }
}

function
  _overrides_set() {
  if ( measure_unit == "" ) {
    measure_unit = "ether";
  }
  if ( retries_max == "" ) {
    retries_max =
      "3";
  }
}

function
  _config_show() {
  let
    _line,
    _text;
  _text = [
    `        Target amount: ${target_amount}`,
    `         Measure unit: ${measure_unit}`
    `    Network options:`,
    `       Target network: ${target_network}`,
    `              API Key: ${api_key}`,
    `Credentials options:`,
    `          Wallet seed: ${wallet_seed}`,
  ]
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line,
    _text;
  _text = [
    "Checks if wallet balance is more or less than a given amount.",
    "",
    "Usage:",
    "  balance-check",
    "    <quiet>",
    "    <seed-path>",
    "    <amount>",
    "    (<target-network>)",
    "    (<api-key>)",
    "    (<measure-unit>)",
    "",
    "Arguments:",
    "  <seed-path>         Path on disk of the file",
    "                      containing the seed phrase.",
    "  <amount>            How much balance to send.",
    "",
    "Optional arguments:",
    "  <target-network>    Name of the network to connect to.",
    "  <api-key>           Path on disk of the API key for",
    "                      the network service provider.",
    "                      Default: the wallet address.",
    "                      corresponding to the seed.",
    "  <measure-unit>      Can be 'wei' or 'ether'.",
    `                      Default: '${display_unit}'`,
    "  <retries-max>       Maximum number of retries.",
    `                      Default: ${retries_max}`,
  ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  _exit(
    _exit_code);
}

function
  _cmdline_parse() {
  let
    _msg;
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        wallet_seed =
          _value;
      }
      if ( _index == 4 ) {
        target_amount =
          _value;
      }
      if ( _index == 5 ) {
        target_network =
          _value;
      }
      if ( _index == 6 ) {
        api_key =
          _value;
      }
      if ( _index == 7 ) {
        measure_unit =
          _value;
      }
      if ( _index == 8 ) {
        retries_max =
          _value;
      }
  });
  if ( wallet_seed == "" ) {
    _msg =
      "No input seed file path.";
    _overrides_set();
    _usage(
      1);
  }

  if ( target_amount == "") {
    _msg =
      "No input amount.";
    _overrides_set();
    _usage(
      1);
  }
}

async function
  _balance_check_cmdline(
    _app_opts) {
  let
    _check;
  try {
    _check =
      await _balance_check.apply(
        null,
        _app_opts);
    process.stdout.write(
      _check.toString());
  }
  catch(
    _error) {
    _msg_error(
      _error,
      1);
  }
}

if ( _cmdline_check(
       "balance-check") ) {
  _global_variables();
  _cmdline_parse();
  _config_show();
  app_opts = [
    wallet_seed,
    target_amount,
    target_network,
    api_key,
    measure_unit,
    retries_max,
  ];
  _balance_check_cmdline(
    app_opts);
}

module.exports = {
  _balance_check:
    _balance_check,
  _msg_error_balance_insufficient:
    _msg_error_balance_insufficient
};
