#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     balance-send
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public
 *     License along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    require(
      "crash-js");
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _basename */
const
  _basename =
    _libcrash._basename;
/* global
     _dirname */
const
  _dirname =
    _libcrash._dirname;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _file_read */
const
  _file_read =
    _libcrash._file_read;
/* global
     _path_join */
const
  _path_join =
    _libcrash._path_join;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_info_obj */
const
  _msg_info_obj =
    _libcrash._msg_info_obj;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _require */
const
  _require =
    _libcrash._require;
const
  { ethers } =
    _require(
      "ethers");
const
  _ethers =
    ethers;
/* global
     _parse_units */
const
  _parse_units =
    _ethers.parseUnits;

const
  _wallet_get_module =
    require(
      './wallet-get');
/* global
     _wallet_get */
const
  _wallet_get =
    _wallet_get_module._wallet_get;
const
  _balance_check_module =
    require(
      './balance-check');
/* global
     _balance_check */
const
  _balance_check =
    _balance_check_module._balance_check;
/* global
     _msg_error_balance_insufficient */
const
  _msg_error_balance_insufficient =
    _balance_check_module._msg_error_balance_insufficient
const
  _network_provider_module =
    require(
      './network-provider');
/* global
     _provider_get */
const
  _provider_get =
    _network_provider_module._provider_get;
/* global
     _msg_info_provider_generated */
const
  _msg_info_provider_generated =
    _network_provider_module._msg_info_provider_generated;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "balance-send";
  /* global
       app_opts:
         writable */
  app_opts =
    [];
  /* global
       method_args:
         writable */
  method_args =
    [];
  /* global
       wallet_seed:
         writable */
  wallet_seed =
    "";
  /* global
       target_address:
         writable */
  target_address =
    "";
  /* global
       target_amount:
         writable */
  target_amount =
    "";
  /* global
       target_network:
         writable */
  target_network =
    "";
  /* global
       api_key:
         writable */
  api_key =
    "";
  /* global
       measure_unit:
         writable */
  measure_unit =
    "";
  /* global
       call_timeout:
         writable */
  call_timeout =
    "";
  /* global
       quiet:
         writable */
  quiet =
    "";
}


function
  _ethers_to_wei(
    _amount) {
  return _parse_units(
    _amount,
    "ether");
}

function
  _send_msg_info(
    _target_amount,
    _amount,
    _measure_unit,
    _measure_unit_converted,
    _target_address) {
  let
    _msg;
  _msg =
    `Sending '${_target_amount}' '${_measure_unit}' `;
  if ( _measure_unit_converted != _measure_unit ) {
    _msg =
      _msg +
      `('${_amount}' ` +
      `'${_measure_unit_converted}') `;
  }
  _msg =
    _msg +
    `to address '${_target_address}'.`;
  _msg_info(
    _msg);
}

async function
  _balance_send(
    _wallet_seed,
    _target_address,
    _target_amount,
    _target_network,
    _api_key_path,
    _measure_unit,
    _call_timeout,
    _verbose) {
  let
    _amount,
    _balance_check_opts,
    _measure_unit_converted,
    _msg,
    _provider_get_opts,
    _send_opts;
  if ( typeof(
         _call_timeout) === "undefined"  ||
         _call_timeout == "" ) {
    _call_timeout =
      300000;
  }
  if ( typeof(
         _measure_unit) === "undefined"  ||
         _measure_unit == "" ) {
    _measure_unit =
      "ether";
  }
  if ( typeof(
         _verbose) === "undefined"  ||
         _verbose == "" ) {
    _verbose =
      "n";
  }
  const
    _wallet_password =
      "";
  const
    _wallet_dir =
      _dirname(
        _wallet_seed);
  const
    _wallet_path_list = [
      _wallet_dir,
      "wallet.dat"
    ];
  const
    _wallet_path =
      _path_join(
        _wallet_path_list);
  _provider_get_opts = [
    _target_network
  ];
  if ( _api_key_path != "" ) {
    const
      _api_key =
        _file_read(
          _api_key_path);
    _provider_get_opts.push(
      _api_key);
  }
  const
    _provider =
      await _provider_get.apply(
        null,
        _provider_get_opts);
  _msg_info_provider_generated(
    _provider);
  const
    _wallet_get_opts = [
      _wallet_path,
      _wallet_password,
      _wallet_seed,
      _provider
    ];
  const
    _wallet =
      _wallet_get.apply(
        null,
        _wallet_get_opts);
  const
    _sender_address =
      _wallet.address;
  _balance_check_opts = [
    _wallet_seed,
    _target_amount,
    _target_network,
    _api_key_path,
    _measure_unit
  ];
  _check =
    await _balance_check.apply(
      null,
      _balance_check_opts);
  if ( _check == false ) {
    _msg_error_balance_insufficient(
      _target_amount,
      _measure_unit);
  }
  _measure_unit_converted =
    _measure_unit;
  if ( _measure_unit == "wei" ) {
    _amount =
      _target_amount;
  }
  else if ( _measure_unit == "ether" ) {
    _amount =
      _ethers_to_wei(
        _target_amount);
    _measure_unit_converted =
      "wei";
  }
  _send_msg_info(
    _target_amount,
    _amount,
    _measure_unit,
    _measure_unit_converted,
    _target_address);
  _send_opts = {
    'to':
      _target_address,
    'value':
      _amount
  };
  const
    _tx =
      await _wallet.sendTransaction(
        _send_opts);
  if ( _verbose == "y" ) {
    _msg =
      "Transaction response:";
    _msg_info(
      _msg);
    console.log(
      _tx);
  }
  const
    _receipt =
      await _tx.wait(
        1,
        _call_timeout);
  if ( _verbose == "y" ) {
    _msg =
      "Transaction receipt:";
    _msg_info(
      _msg);
    console.log(
      _receipt);
  }
  return [ _tx, _receipt ];
}

function
  _overrides_set() {
  let
    _info_get,
    _target_network_type;
  _info_get =
    false;
  _target_network_type =
    typeof(
      target_network);
  if ( _target_network_type == "undefined" ||
       target_network == "" ) {
    target_network = 100;
    _target_network_type =
      typeof(
        target_network);
  }
  if ( _target_network_type == "number" ) {
    _info_get =
      true;
  }
  else if ( _target_network_type == "string" ) {
    if ( ! target_network.startsWith(
           "https://") ) {
      _info_get =
        true;
    }
  }
  else {
    const
      _msg =
        `Unknown type '${_target_network_type}' ` +
        `for network variable.`;
    _msg_error(
      _msg,
      1);
  }
  if ( _info_get ) {
    const
      _libevm_module =
        _require(
          "libevm");
    const
      _rpc_get =
        _libevm_module._rpc_get;
    target_network =
      _rpc_get(
        [ target_network ])[
        target_network];
  }
  if ( typeof(
         measure_unit) == "undefined" ||
       measure_unit == "" ) {
    measure_unit = "ether";
  }
  if ( typeof(
         call_timeout) == "undefined" ||
       call_timeout == "" ) {
    call_timeout = "ether";
  }
}

function
  _config_show() {
  let
    _line;
  const
    _argv =
      _argv_get();
  const
    _program =
      _basename(
        _argv[
          "$0"]);
  const
    _text = [
      `  ${_program} configuration:`,
      `      Wallet seed: ${wallet_seed}`,
      `   Target address: ${target_address}`,
      `    Target amount: ${target_amount}`,
      `   Target network: ${target_network}`,
      `          API Key: ${api_key}`,
      `     Measure unit: ${measure_unit}`,
      `     Call timeout: ${call_timeout}`,
    ]
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  if ( typeof(
         _exit_code) == "undefined" ||
       _exit_code == "" ) {
    _exit_code =
      0;
  }
  const
    _argv =
      _argv_get();
  const
    _program =
      _basename(
        _argv[
          "$0"]);
  const
    _text = [
      "Transfer gas from an address to another.",
      "",
      "Usage:",
      `  ${_program}`,
      "    <quiet>",
      "    <seed-path>",
      "    <target-address>",
      "    <amount>",
      "  ( <target-network>",
      "    <api-key>",
      "    <measure-unit>",
      "    <call-timeout> )",
      "",
      "Args:",
      "",
      "  <seed-path>         Path on disk of the file",
      "                      containing the seed phrase.",
      "",
      "  <target-address>    Address to send some balance to.",
      "",
      "  <amount>            How much balance to send.",
      "",
      "  <target-network>    Name of the network to connect to.",
      `                      Default: ${target_network}`,
      "",
      "  <api-key>           Path on disk of the API key for",
      "                      the network service provider.",
      "                      Default: the wallet address.",
      "",
      "  <measure-unit>      Can be 'wei' or 'ether'.",
      `                      Default: ${measure_unit}`,
      "",
      "  <call-timeout>      Timeout before declaring the call failed.",
      `                      Default: ${call_timeout}`,
    ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  _exit(
    _exit_code);
}

function _cmdline_parse() {
  let
    _msg;
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        wallet_seed =
          _value;
      }
      if ( _index == 4 ) {
        target_address =
          _value;
      }
      if ( _index == 5 ) {
        target_amount =
          _value;
      }
      if ( _index == 6 ) {
        target_network =
          _value;
      }
      if ( _index == 7 ) {
        api_key =
          _value;
      }
      if ( _index == 8 ) {
        measure_unit =
        _value;
      }
      if ( _index == 9 ) {
        call_timeout =
        _value;
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        _overrides_set();
        quiet =
          "n";
        _usage(
          0);
      }
  });
  if ( typeof(
         wallet_seed) == "undefined" ||
       wallet_seed == "") {
    _msg =
      "No seed phrase given in input.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  if ( typeof(
         target_address) == "undefined" ||
       target_address == "") {
    _overrides_set();
    quiet =
      "n";
    _msg =
      "No target address given in input.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
  if ( typeof(
         target_amount) == "undefined" ||
       target_amount == "") {
    _overrides_set()
    _msg =
      "No target address given in input.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
}

async function
  _balance_send_cmdline(
    app_opts) {
  let
    _receipt,
    _tx;
  [ _tx,
    _receipt ] =
  await _balance_send.apply(
    null,
    app_opts);
  console.log(
    "Transaction response:");
  console.log(
    _tx);
  console.log(
    "Transaction receipt:");
  console.log(
    _receipt);
}

if ( _cmdline_check(
        "balance-send") ||
      _cmdline_check(
        "gas-transfer") ) {
  _global_variables();
  _cmdline_parse();
  _overrides_set();
  _config_show();
  app_opts = [
    wallet_seed,
    target_address,
    target_amount,
    target_network,
    api_key,
    measure_unit,
    call_timeout
  ];
  _balance_send_cmdline.apply(
    null,
    app_opts);
}

module.exports = {
  _balance_send:
    _balance_send,
  _ether_to_wei:
    _ether_to_wei,
  _ethers_to_wei:
    _ether_to_wei
};
