#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later


/**    ----------------------------------------------------------------
 *     block-number-get
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _argv_get */
const
  _argv_get =
    _libcrash._argv_get;
/* global
     _basename */
const
  _basename =
    _libcrash._basename;
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _dirname */
const
  _dirname =
    _libcrash._dirname;
/* global
     _echo */
const
  _echo =
    _libcrash._echo;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _file_read */
const
  _file_read =
    _libcrash._file_read;
/* global
     _file_write */
const
  _file_write =
    _libcrash._file_write;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_info_obj */
const
  _msg_info_obj =
    _libcrash._msg_info_obj;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _path_join */
const
  _path_join =
    _libcrash._path_join;
/* global
     _require */
const
  _require =
    _libcrash._require;
/* global
     _run */
const
  _run =
    _libcrash._run;
/* global
     _sleep */
const
  _sleep =
    _libcrash._sleep;
const
  _wallet_get_module =
    await import(
      './wallet-get');
/* global
     _wallet_get */
const
  _wallet_get =
    _wallet_get_module._wallet_get;
const
  _network_provider =
    await import(
      './network-provider');
/* global
     _provider_get */
const
  _provider_get =
    _network_provider._provider_get;
/* global
     _msg_info_provider_generated */
const
  _msg_info_provider_generated =
    _network_provider._msg_info_provider_generated;

function
  _global_variables() {
  app_name =
    "block-number-get";
  /* global
       wallet_seed:
         writable */
  wallet_seed =
    "";
  /* global
       target_network:
         writable */
  target_network =
    "";
  /* global
       api_key:
         writable */
  api_key =
    "";
  /* global
       target_address:
         writable */
  target_address =
    "";
  /* global
       output_file:
         writable */
  output_file =
    "";
  /* global
       retries_max:
         writable */
  retries_max =
    "";
  /* global
       call_timeout:
         writable */
  call_timeout =
    "";
  /* global
       quiet:
         writable */
  quiet =
    "";
}

async function
  _block_number_get(
    _target_network,
    _api_key_path,
    _output_file,
    _retries_max,
    _call_timeout) {
  let
    _block_number,
    _msg,
    _provider_get_opts,
    _retry,
    _request,
    _success,
    _time_over;
  if ( typeof(
         _retries_max) == 'undefined' ||
       _retries_max == "" ) {
    _retries_max =
      3;
  }
  else {
    _retries_max =
      Number(
        _retries_max);
  }
  if ( typeof(
         _call_timeout) == 'undefined' ||
       _call_timeout == "" ) {
    _call_timeout =
      100000;
  }
  _retry =
    0;
  _success =
    false;
  _provider_get_opts = [
    _target_network,
  ];
  if ( _output_file == undefined ) {
    _output_file =
      "";
  }
  if ( _api_key_path != "" ) {
    _api_key =
      _file_read(
        _api_key_path);
    _provider_get_opts.push(
      _api_key);
  }
  _provider_get_opts.push(
    _call_timeout);
  _provider =
    await _provider_get.apply(
      null,
      _provider_get_opts);
  _msg_info_provider_generated(
    _provider);
  _msg =
    `Retrieving block number for ` +
    `network '${_target_network}'.`;
  _msg_info(
    _msg);
  while ( _success == false &&
          _retry < _retries_max ) {
    try {
      const
        _provider_get_block_number_cmd = [
          _provider
        ];
      _block_number =
        await _run(
          "sync",
          _provider_get_block_number_cmd,
          "_provider_get_block_number",
          _call_timeout,
          "native",
          "getBlockNumber");
      if ( typeof(
             _block_number) == "undefined" ) {
        const
          _error = {
            "message":
              "Timeout reached for block number retrieval."
          };
        throw _error;
      }
      if ( _output_file != "" ) {
          _file_write(
            _output_file,
            _block_number.toString());
      }
      _success =
        true;
    } catch(
        _error) {
      _retry =
        _retry + 1;
      _msg =
        `Error retrieving block number `+
        `from network/rpc '${_target_network}', ` +
        `retrying (${_retry} of ${_retries_max})`;
      console.error(
        _error);
      _msg_error(
        _msg,
        0);
      await _provider.destroy();
      await _sleep(
        3000);
      _provider =
        await _provider_get.apply(
          null,
          _provider_get_opts);
    }
  }
  if ( _success == false &&
       _retry == _retries_max ) {
    _provider.destroy();
    _msg =
      "Failed retrieving block number" +
      `from network '${_target_network}'.`;
    throw _msg;
  }
  return _block_number;
}

async function
  _overrides_set() {
  let
    _info_get;
  _info_get =
    false;
  const
    _target_network_type =
      typeof(
        target_network);
  if ( _target_network_type == "number" ) {
    _info_get =
      true;
  }
  else if ( _target_network_type == "string" ) {
    if ( ! target_network.startsWith(
           "https://") ) {
      _info_get =
        true;
    }
  }
  else {
    const
      _msg =
        `Unknown type '${_target_network_type}' ` +
	`for network variable.`;
    _msg_error(
      _msg,
      1);
  }
  if ( _info_get ) {
    const
      _libevm_module =
        await _require(
          "libevm");
    const
      _rpc_get =
        _libevm_module._rpc_get;
    target_network =
      _rpc_get(
        [ target_network ])[
        target_network];
  }
  if ( typeof(
         retries_max) == "undefined" ||
       retries_max == "" ) {
    retries_max =
      "1";
  }
  if ( typeof(
         call_timeout) == "undefined" ||
       call_timeout == "" ) {
    call_timeout =
      "30000";
  }
}

async function
  _config_show() {
  let
    _line;
  const
    _argv =
      await _argv_get();
  const
    _program =
      _basename(
        _argv[
          "$0"]);
  const
    _text = [
      `  ${_program} configuration:`,
      `   Target network: ${target_network}`,
      `          API Key: ${api_key}`,
      `      Output file: ${output_file}`,
      `  Maximum retries: ${retries_max}`,
      `     Call timeout: ${call_timeout}`
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  if ( typeof(
         _exit_code) == "undefined" ||
       _exit_code == "" ) {
    _exit_code =
      0;
  }
  const
    _argv =
      _argv_get();
  const
    _program =
      _basename(
        _argv[
          "$0"]);
  const
    _text = [
      "Returns current block number for a blockchain network",
      "",
      "Usage:",
      `  ${_program}`,
      "    <quiet>",
      "    <target-network>",
      "  ( <api-key-path",
      "    <output-file>",
      "    <retries-max>",
      "    <call-timeout> )",
      "",
      "Arguments:",
      "",
      "  <target-network>    Name, chain ID or RPC address",
      "                      of the network to connect to.",
      "",
      "Optional arguments:",
      "",
      "  <api-key-path>      Path on disk of the API key for",
      "                      the network service provider.",
      "",
      "  <output-file>       File in which to save the block number.",
      `                      Default: '${output_file}'`,
      "",
      "  <retries-max>       Maximum number of retries.",
      `                      Default: ${retries_max}`,
      "",
      "  <call-timeout>      Timeout before declaring the call failed.",
      `                      Default: ${call_timeout}`,
  ];
  for ( _line of _text ) {
    _echo(
      _line);
  }
  _exit(
    _exit_code);
}


async function
  _cmdline_parse() {
  let
    _help_display,
    _msg;
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        target_network =
          _value;
      }
      if ( _index == 4 ) {
        api_key =
          _value;
      }
      if ( _index == 5 ) {
        output_file =
          _value;
      }
      if ( _index == 6 ) {
        retries_max =
          _value;
      }
      if ( _index == 7 ) {
        call_timeout =
          _value;
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        _help_display =
          true;
      }
  });
  if ( _help_display ) {
    await _overrides_set();
    quiet =
      "n";
    _usage(
      0);
  }
  if ( target_network == "" ) {
    _msg =
      "No network given in input.";
    _msg_error(
      _msg,
      0);
    await _overrides_set();
    _usage(
      1);
  }
}

async function
  _block_number_get_cmdline(
    _app_opts) {
  let
    _block_number;
  try {
    _block_number =
      await _block_number_get.apply(
        null,
        _app_opts);
    _echo(
      _block_number.toString());
    // process.stdout.write(
    //   _block_number.toString());
    _exit(
      0);
  }
  catch(
    _error) {
    _msg_error(
      _error,
      1);
  }
}

async function
  _main() {
  _global_variables();
  await _cmdline_parse();
  await _overrides_set();
  await _config_show();
  app_opts = [
    target_network,
    api_key,
    output_file,
    retries_max,
    call_timeout
  ];
  const
    _return =
      _block_number_get_cmdline(
        app_opts);
  _echo(
    _return);
}

if ( await _cmdline_check(
       "block-number-get") == true ||
     await _cmdline_check(
       "block-number") == true ) {
  _main();
}

export {
  _block_number_get
};

// module.exports = {
//   _block_number_get:
//     _block_number_get
// };
