#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _argv:
       writable */
const
  _argv =
    _libcrash._argv;
/* global
     _basename:
       writable */
const
  _basename =
    _libcrash._basename;
/* global
     _cmdline_check:
       writable */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _echo:
       writable */
const
  _echo =
    _libcrash._echo;
/* global
     _exit:
       writable */
const
  _exit =
    _libcrash._exit;
/* global
     _get:
       writable */
const
  _get =
    _libcrash._get;
/* global
     _global_get:
       writable */
const
  _global_get =
    _libcrash._global_get;
/* global
     _msg_error:
       writable */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _msg_info:
       writable */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _require:
       writable */
const
  _require =
    _libcrash._require;
/* global
     _set:
       writable */
const
  _set =
    _libcrash._set;
const
  _ethers_module =
    await _require(
      "ethers");
/* global
     _ethers */
const
  _ethers =
    _ethers_module.ethers;
/* global
     _wei_to_ether:
       writable */
const
  _wei_to_ether =
    _ethers.formatEther;
/* global
     _parse_units:
       writable */
const
  _parse_units =
    _ethers.parseUnits;

function
  _global_variables() {
  _set(
    "app",
    "name",
    "ethers-to-wei");
  _set(
    "ethers",
    "input",
    "");
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "";
}

function
  _ethers_to_wei(
    _amount) {
  let
    _amount_string
  _amount_string = String(
    _amount);
  return _parse_units(
    _amount_string,
    "ether");
}

const
  _ether_to_wei =
    _ethers_to_wei;

function
  _config_show() {
  let
    _line;
  const
    _text = [
      "     Input ethers: {ethers_input}".replaceAll(
        "{ethers_input}",
        ethers_input),
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _program =
      _basename(
        _argv[
          "1"]);
  const
    _text = [
      "",
      "Converts ethers in wei",
      "",
      "Usage:",
      `  ${_program}`,
      "    <ethers-input>",
      ""
    ];
  for ( _line of _text ) {
    _echo(
      _line);
  }
  _exit(
    _exit_code);
}


async function
  _cmdline_parse() {
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "y";
  _argv.forEach(
    function (
      _value,
      _index) {
      if ( _index == 2 ) {
        _set(
          "ethers",
          "input",
          _value);
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        _global[
          "quiet"] =
          "n";
        _usage(
          0);
      }
  });
  const
    _ethers_input =
      _get(
        "ethers",
        "input");
  if ( _ethers_input == "" ) {
    const
      _msg =
        "No arguments given.";
    _msg_error(
      _msg,
      0);
    _global[
      "quiet"] =
      "n";
    _usage(
      0);
  }
}

if ( await _cmdline_check(
       "ethers-to-wei") ||
     await _cmdline_check(
       "ethers-to-wei.js") ||
     await _cmdline_check(
       "ether-to-wei") ||
     await _cmdline_check(
       "ether-to-wei.js") ||
     await _cmdline_check(
       "ether2wei") ||
     await _cmdline_check(
       "ether2wei.js") ) {
  _global_variables();
  _cmdline_parse();
  _config_show();
  const
    _wei =
      String(
        _ethers_to_wei(
          ethers_input));
  _echo(
    _wei);
}

export {
  _ether_to_wei,
  _ethers_to_wei
};

// module.exports = {
//   _ethers_to_wei:
//     _ethers_to_wei,
//   _ether_to_wei:
//     _ether_to_wei
// };
