#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     network-provider
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public
 *     License along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    require(
      "crash-js");
/* global
     _cmdline_check:
       writable */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _exit:
       writable */
const
  _exit =
    _libcrash._exit;
/* global
     _msg_info:
       writable */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_error:
       writable */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _require:
       writable */
const
  _require =
    _libcrash._require;
const
  _ethers_module =
    await _require(
      "ethers");
/* global
     _ethers */
const
  _ethers =
    _ethers_module.ethers;
/* global
     _fetch_request:
       writable */
const
  _fetch_request =
    _ethers.FetchRequest;
/* global
     _get_default_provider:
       writable */
const
  _get_default_provider =
    _ethers.getDefaultProvider;
/* global
     _json_rpc_provider:
       writable */
const
  _json_rpc_provider =
    _ethers.JsonRpcProvider;
/* global
     _network_class:
       writable */
const
  _network_class =
    _ethers.Network;


function
  _global_variables() {
  app_name =
    "network-provider";
  target_network =
    "";
  api_key =
    "";
  chain_id =
    "";
  chain_name =
    "";
  connection_timeout =
    "";
}

function
  _msg_info_provider_generated(
    _provider) {
  let
    _get_connection_type,
    _key,
    _timeout,
    _msg;
  const
    _provider_type =
      typeof(
        _provider);
  // Really it's always object.
  if ( _provider_type == "undefined" ) {
    _msg =
      "Provider undefined."
    _error = {
      "error":
        _msg };
    throw _error;
  }
  else if ( _provider_type == "object" ) {
    _get_connection_type =
      typeof(
        _provider._getConnection);
    if ( _get_connection_type == "undefined" ) {
      _msg =
        "Probably a dummy connection method";
      _msg_info(
        _msg);
    }
    else if ( _get_connection_type == "JsonRpcProvider" ) {
      _get_connection_type =
        typeof(
          _provider._getConnection);
      _msg =
        "Json RPC provider."
      _msg_info(
        _msg);
      if ( _get_connection_type != "undefined" ) 
        _timeout =
          _provider._getConnection().timeout;
        _msg =
          `Provider '${_provider}' with ` +
          `timeout '${_timeout}' generated.`;
        _msg_info(
          _msg);
    }
    else {
      // _msg =
      //   "The provider has no '_getConnection' method.";
      // _msg_info(
      //   _msg);
      // if ( quiet == "n" ) {
      //   console.log(
      //     typeof(
      //       _provider));
      //   console.log(
      //     _provider.connection);
      // }
      for ( _key in _provider) {
        _msg=
          `Provider key: ${_key}, ` +
          `value '${_provider[_key]}'`;
        _msg_info(
          _msg);
      }
    }
  }
}

function
  _target_networks_check(
    _target_networks) {
  let
    _target_network,
    _target_network_type;
  const
   _target_networks_type =
     typeof(
       _target_networks);
  if ( _target_networks_type == "undefined" ||
       _target_networks == [] ||
       _target_networks == "" ) {
    _target_networks =
      [];
  }
  if ( 0 < _target_networks.length ) {
    _target_network =
      _target_networks[
        0];
      _target_network_type =
        typeof(
          _target_network);
    if ( _target_network_type == "object" ) {
      _target_networks =
        _target_network;
    }
  }
  else {
    _target_network =
      "";
  }
  if ( _target_networks.length == 1 ) {
    _target_network =
      _target_networks[
        0];
      _target_network_type =
        typeof(
          _target_network);
    if ( _target_network_type == "string" ) {
      if ( _target_network.includes(
             ",") ) {
        const
          _commas =
            _target_network.split(",");
        if ( 1 < _commas.length ) {
          _target_networks =
            _commas;
        }
      }
    }
  }
  return [ _target_networks,
           _target_network ];
}

function
  _rpc_auto_detect(
    _chain_id) {
  let
    _target_networks;
  const
    _libevm_module =
      require(
        "libevm");
  const
    _rpc_get =
      _libevm_module._rpc_get;
  _target_networks = [
    _chain_id
  ];
  [ _target_networks,
    _target_network ] =
    _target_networks_check(
      _target_networks);
  const
    _rpc =
      _rpc_get(
        _target_networks)[
          _chain_id];
  return _rpc;
}

async function
  _provider_get(
    _target_network,
    _api_key,
    _chain_id,
    _chain_name,
    _timeout,
    _timeout_set) {
  let
    _default_network,
    _get_default_provider_opts,
    _msg,
    _network,
    _network_new_opts,
    _provider,
    _provider_opts,
    _rpc;
  const
    _network_type =
      typeof(
        _target_network);
  const
    _chain_id_type =
      typeof(
        _chain_id);
  if ( _network_type == "undefined" ||
       _target_network == "" ) {
    if ( _chain_id_type != "undefined" &&
         _chain_id != "" ) {
      _msg =
        "Getting RPC for network with " +
        `chain ID '${_chain_id}'.`;
      _msg_info(
        _msg);
      _target_network =
        _rpc_auto_detect(
          _chain_id);
    }
    else {
      _msg =
        "No network or chain id given in input, " +
        "will return empty provider.";
      _msg_info(
        _msg);
    }
  }
  if ( ! _target_network.startsWith(
           "https://") &&
       ! _target_network.startsWith(
           "wss://") ) {
    _msg =
      "Given chain ID as a network url, " +
      "obtaining an RPC url for the " +
      `network with chain ID '${_chain_id}'.`;
    _msg_info(
      _msg);
    _target_network =
      _rpc_auto_detect(
        _target_network);
  }
  if ( typeof(
         _timeout) == "undefined" ||
       _timeout == "" ) {
    _timeout =
      300;
    _timeout_set =
      false;
  }
  else {
    _timeout_set =
      true;
  }
  _timeout =
    Number(
      _timeout);
  _get_default_provider_opts =
    [];
  _network_new_opts = [
    null
  ];
  _provider_opts =
    {};
  if ( _target_network == "gnosis" ) {
    _rpc =
      "https://rpc.gnosischain.com";
    _default_network = _rpc;
  } 
  else if ( _target_network == "ethereum" ) {
    if ( _api_key != "" ) {
      _default_network =
        "etherscan";
      _provider_opts = {
        'etherscan':
          _api_key,
        'exclusive': [
          "etherscan",
          "infura"
        ]
      };
    }
    else {
      _rpc =
        "https://rpc.ankr.com/eth";
      _default_network =
        _rpc;
    }
  }
  else {
    _default_network =
      _target_network;
  }
  if ( _default_network == "" ) {
    _default_network =
      "mainnet";
  }
  _get_default_provider_opts.push(
    _default_network);
  if ( _chain_name == "" ||
       _chain_name == undefined ||
       _chain_name == null ) {
    _chain_name =
      "";
  }
  _network_new_opts.push(
    _chain_name);
  if ( _chain_id != "" &&
       _chain_id != undefined &&
       _chain_id != null && 
       ( ! isNaN(
             _chain_id) ) ) {
    _chain_id =
      Number(
        _chain_id);
    _network_new_opts.push(
      _chain_id);
  }
  if ( 2 < _network_new_opts.length ) {
    _network =
      new (Function.prototype.bind.apply(
        _network_class,
        _network_new_opts));
    _get_default_provider_opts.push(
     _network); 
  }
  if ( _timeout_set == true ) {
    if ( _default_network.startsWith(
           "http") ) {
      _request =
        new _fetch_request(
          _default_network);
      _request._getConnection().timeout =
        _timeout;
      _provider =
        await new _json_rpc_provider(
	  _request);
    }
  }
  else if ( _timeout_set == false ) {
    _get_default_provider_opts.push(
      _provider_opts);
  }
  _provider =
    await _get_default_provider.apply(
      null,
      _get_default_provider_opts);
  _msg_info_provider_generated(
    _provider);
  return _provider;
}

function
  _config_show() {
  let
    _line,
    _text;
  _text = [
    `   Target network: ${target_network}`,
    `          API Key: ${api_key}`,
    `         Chain ID: ${chain_id}`,
    `       Chain Name: ${chain_name}`,
    `          Timeout: ${connection-timeout}`
  ]
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line,
    _text;
  _text = [
    "Usage:",
    "  network-provider",
    "    <target-network>",
    "    <api-key-path>",
    "    (<chain-id>)",
    "    (<chain-name>)",
    "",
    "Args:",
    "  <target-network>                 Network on which the transaction",
    "                                   resides.",
    "  <api-key-path>                   Path of the API key for the",
    "                                   contract ABI provider service.",
    "  <chain-id>                       Chain ID for the network.",
    "  <chain-name>                     Name for the network.",
    "",
    "  Options:",
    "    -h                             This help."
  ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  if ( -1 < _exit_code ) {
    _exit(
      _exit_code);
  }
}

function
  _cmdline_parse() {
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        target_network =
          _value;
      }
      if ( _index == 3 ) {
        api_key =
          _value;
      }
      if ( _index == 4 ) {
        chain_id =
          _value;
      }
      if ( _index == 5 ) {
        chain_name =
          _value;
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        quiet =
          "n";
        _usage(
          0);
      }
    }
  );
  if ( target_network == "" ) {
    quiet =
      "n";
    _usage(
      1);
  }
}

function
  _overrides_set() {
  if ( target_network == "" ) {
    // But really.
    target_network =
      "gnosis";
  }
  if ( connection_timeout == "" ) {
    connection_timeout =
      "300000";
  }
}

if ( _cmdline_check(
       "network-provider") ) {
  _global_variables();
  _cmdline_parse();
  _overrides_set();
  _config_show();
  app_opts = [
    target_network,
    api_key,
    chain_id,
    chain_name,
    connection_timeout
  ];
  _provider_get.apply(
    null,
    app_opts);
}

module.exports = {
  _provider_get:
    _provider_get,
  _msg_info_provider_generated:
    _msg_info_provider_generated,
  _target_networks_check:
    _target_networks_check
};

