#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/* Crash Javascript global variables */

/* global
    quiet:
      writable */

const
  _libcrash =
    require(
      "crash-js");
/* global
    _dirname:
      writable */
const
  _dirname =
    _libcrash._dirname;
/* global
    _exit:
      writable */
const
  _exit =
    _libcrash._exit;
/* global
    _file_read:
      writable */
const
  _file_read =
    _libcrash._file_read;
/* global
    _file_write:
      writable */
const
  _file_write =
    _libcrash._file_write;
/* global
    _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
    _path_join:
      writable */
const
  _path_join =
    _libcrash._path_join;
/* global
    _msg_info:
      writable */
const
  _msg_info =
    _libcrash._msg_info;
/* global
    _msg_info_obj:
      writable */
const
  _msg_info_obj =
    _libcrash._msg_info_obj;
/* global
    _msg_error:
      writable */
const
  _msg_error =
    _libcrash._msg_error;
/* global
    _require:
      writable */
const
  _require =
    _libcrash._require;
/* global
    _sleep:
      writable */
const
  _sleep =
    _libcrash._sleep;
const
  _ethers_module =
    await _require(
      "ethers");
/* global
     _ethers */
const
  _ethers =
    _ethers_module.ethers;
/* global
    _wei_to_ether:
      writable */
const
  _wei_to_ether =
    _ethers.formatEther;
const
  _wallet_get_module =
    require(
      './wallet-get');
/* global
    _wallet_get:
      writable */
const
  _wallet_get =
    _wallet_get_module._wallet_get;
const
  _network_provider_module =
    require(
      './network-provider');
/* global
    _provider_get:
      writable */
const
  _provider_get =
    _network_provider_module._provider_get;
/* global
    _msg_info_provider_generated:
      writable */
const
  _msg_info_provider_generated =
    _network_provider_module._msg_info_provider_generated;

function
  _global_variables() {
  /* global
      app_name:
        writable */
  app_name =
    "price-gas-get";
  /* global
      app_opts:
        writable */
  app_opts =
    [];
  /* global
      wallet_seed:
        writable */
  wallet_seed =
    "";
  /* global
      target_network:
        writable */
  target_network =
    "";
  /* global
      api_key:
        writable */
  api_key =
    "";
  /* global
      target_address:
        writable */
  target_address =
    "";
  /* global
      display_unit:
        writable */
  display_unit =
    "";
  /* global
      output_type:
        writable */
  output_type =
    "";
  /* global
      output_file:
        writable */
  output_file =
    "";
  /* global
      retries_max:
        writable */
  retries_max =
    "";
  quiet =
    "";
}


async function
  _price_gas_get(
    _target_network,
    _api_key_path,
    _display_unit,
    _wallet_seed,
    _target_address,
    _output_type,
    _output_file,
    _retries_max,
    _verbose) {
  let
    _fee_data,
    _msg,
    _price_gas,
    _price_gas_ether,
    _price_gas_wei,
    _provider_get_opts,
    _retry,
    _request,
    _success,
    _wallet_dir,
    _wallet_password,
    _wallet_path_list;
  if ( typeof(
         _verbose) == 'undefined' ||
       _verbose == "" ) {
    _verbose =
      "n";
  }
  if ( typeof(
         _output_type) == 'undefined' ||
       _output_type == "" ) {
    _output_type =
      "price";
  }
  if ( typeof(
         _retries_max) == 'undefined' ||
       _retries_max == "" ) {
    _retries_max =
      3;
  }
  _retries_max =
    Number(
      _retries_max);
  if ( typeof(
         _display_unit) == 'undefined' ||
       _display_unit == "" ) {
    _display_unit =
      "wei";
  }
  _timeout =
    100000;
  _retry =
    0;
  _success =
    false;
  _wallet_password =
    "";
  _wallet_dir =
    _dirname(
      _wallet_seed);
  _wallet_path_list = [
    _wallet_dir,
    "wallet.dat"
  ];
  _wallet_path =
    _path_join(
      _wallet_path_list);
  _provider_get_opts = [
    _target_network,
  ];
  if ( _output_file == undefined ) {
    _output_file =
      "";
  }
  if ( _api_key_path != "" ) {
    _api_key =
      _file_read(
        _api_key_path);
    _provider_get_opts.push(
      _api_key);
  }
  _provider_get_opts.push(
    _timeout);
  _provider =
    await _provider_get.apply(
      null,
      _provider_get_opts);
  _msg_info_provider_generated(
    _provider);
  // if ( _target_address == "" ) {
  //   _wallet_get_opts = [
  //     _wallet_path,
  //     _wallet_password,
  //     _wallet_seed,
  //     _provider
  //   ];
  //   _wallet =
  //     _wallet_get.apply(
  //       null,
  //       _wallet_get_opts);
  //   _target_address =
  //     _wallet.address;
  // }
  while ( _success == false &&
          _retry < _retries_max ) {
    try {
      _fee_data = await
        _provider.getFeeData();
      if ( _verbose == "y" ) {
        console.log(
          _fee_data);
      }
      if ( _output_type == "price" ) {
        _price_gas_wei =
          _fee_data.gasPrice;
      }
      else if ( _output_type == "fee" ) {
        _price_gas_wei =
          _fee_data.maxFeePerGas;
      }
      else if ( _output_type == "priority" ) {
        _price_gas_wei =
        _fee_data.maxPriorityFeePerGas;
      }
      if ( _display_unit == "wei" ) {
        _price_gas =
          _price_gas_wei;
      }
      else if ( _display_unit == "ether" ) {
        _price_gas_ether =
          _wei_to_ether(
            _price_gas_wei);
        _price_gas =
          _price_gas_ether;
      }
      if ( _output_file != "" ) {
          _file_write(
            _output_file,
            _price_gas.toString());
      }
      _success =
        true;
    } catch(
        _err) {
      _retry =
        _retry + 1;
      _msg =
        `Error retrieving gas price, ` +
	`retrying (${_retry} of ${_retries_max})`;
      console.error(
        _err);
      _msg_error(
        _msg,
        0);
      await _sleep(
        3000);
    }
  }
  if ( _success == false &&
       _retry == _retries_max ) {
    throw "Error retrieving balance.";
  }
  return _price_gas;
}

function
  _overrides_set() {
  _override_set(
    "display",
    "unit",
    "wei");
  _override_set(
    "output",
    "type",
    "price");
  _override_set(
    "retries",
    "max",
    "1");
}

function
  _config_show() {
  let
    _line,
    _text;
  _text = [
    `      Wallet seed: ${wallet_seed}`,
    `   Target network: ${target_network}`,
    `          API Key: ${api_key}`,
    `   Target address: ${target_address}`,
    `     Display unit: ${display_unit}`,
    `      Output type: ${output_type}`,
    `      Output file: ${output_file}`,
    `  Maximum retries: ${retries_max}`
  ]
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line,
    _text;
  _text = [
    "Usage:",
    "  price-gas-get",
    "    <quiet>",
    "    <target-network>",
    "    (<api-keys-path)",
    "    (<display-unit>)",
    "    (<seed-path>)",
    "    (<target-address>)",
    "    (<output-type>)",
    "    (<output-file>)",
    "    (<retries-max>)",
    "",
    "Arguments:",
    "  <target-network>    Name of the network to connect to.",
    "",
    "Optional arguments:",
    "  <api-key-path>      Path on disk of the API key for",
    "                      the network service provider.",
    "  <display-unit>      Can be 'wei' or 'ether'.",
    `                      Default: '${display_unit}'`,
    "  <seed-path>         Path on disk of the file",
    "                      containing the seed phrase.",
    "  <target-address>    Address for which to return",
    "                      the gas price (not used).",
    "                      Default: the wallet address.",
    "                      corresponding to the seed.",
    "  <output-type>       Type of price output to return.",
    `                      Default: '${output_type}'`,
    "  <output-file>       File in which to save the balance.",
    `                      Default: '${output_file}'`,
    "  <retries-max>       Maximum number of retries.",
    `                      Default: ${retries_max}`,
  ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  process.exit(
    _exit_code);
}


function _cmdline_parse() {
  let
    _msg;
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        target_network =
          _value;
      }
      if ( _index == 4 ) {
        api_key =
          _value;
      }
      if ( _index == 5 ) {
        display_unit =
          _value;
      }
      if ( _index == 6 ) {
        target_address =
	  _value;
      }
      if ( _index == 7 ) {
        wallet_seed =
          _value;
      }
      if ( _index == 8 ) {
        output_type =
          _value;
      }
      if ( _index == 9 ) {
        output_file =
          _value;
      }
      if ( _index == 10 ) {
        retries_max =
          _value;
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        quiet =
          "n";
        _usage(
          0);
      }
  });
  if ( target_network == "" ) {
    _msg =
      "No input network given."
    _msg_error(
      _msg,
      1);
    _overrides_set();
    _usage(
      1);
  }
}

async function
  _price_gas_get_cmdline(
    _app_opts) {
  let
    _price_gas;
  try {
    _price_gas =
      await _price_gas_get.apply(
        null,
        _app_opts);
    // console.log(
    //   _price_gas.toString());
    // process.stdout.write(
    //   _balance.toString());
  }
  catch(
    _error) {
    _msg_error(
      _error,
      1);
    process.exit(
      1);
  }
}

if ( _cmdline_check(
       "price-gas-get") ) {
  _global_variables();
  _cmdline_parse();
  _config_show();
  app_opts = [
    target_network,
    api_key,
    display_unit,
    wallet_seed,
    target_address,
    output_type,
    output_file,
    retries_max
  ];
  _price_gas_get_cmdline(
    app_opts);
}

module.exports = {
  _price_gas_get:
    _price_gas_get
};
