#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     price-gas-transaction-get
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public
 *     License along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* Crash Javascript global variables */

/* global
     quiet:
       writable */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _dirname */
const
  _dirname =
    _libcrash._dirname;
/* global
     _echo */
const
  _echo =
    _libcrash._echo;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _global_get */
const
  _global_get =
    _libcrash._global_get;
/* global
     _file_read */
const
  _file_read =
    _libcrash._file_read;
/* global
     _file_write */
const
  _file_write =
    _libcrash._file_write;
/* global
     _override_set */
const
  _override_set =
    _libcrash._override_set;
/* global
     _path_join */
const
  _path_join =
    _libcrash._path_join;
/* global
     _msg_info */
const
  _msg_info =
    _libcrash._msg_info;
/* global
     _msg_info_obj */
const
  _msg_info_obj =
    _libcrash._msg_info_obj;
/* global
     _msg_error */
const
  _msg_error =
    _libcrash._msg_error;
/* global
     _set */
const
  _set =
    _libcrash._set;
/* global
     _sleep */
const
  _sleep =
    _libcrash._sleep;
const
  _provider_get_module =
    await import(
      './network-provider');
/* global
     _provider_get */
const
  _provider_get =
    _provider_get_module._provider_get;
const
  _wallet_get_module =
    await import(
      './wallet-get');
/* global
     _wallet_get */
const
  _wallet_get =
    _wallet_get_module._wallet_get;
const
  _price_gas_get_module =
    await import(
      './price-gas-get');
/* global
     _price_gas_get */
const
  _price_gas_get =
    _price_gas_get_module._price_gas_get;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  _set(
    "app",
    "name",
    "price-gas-transaction-get");
  /* global
       app_opts:
         writable */
  _set(
    "app",
    "opts",
    []);
  /* global
       selection_mode:
         writable */
  _set(
    "selection",
    "mode",
    "");
  selection_mode =
    "";
  /* global
       wallet_seed:
         writable */
  wallet_seed =
    "";
  /* global
       target_network:
         writable */
  target_network =
    "";
  /* global
       api_key:
         writable */
  api_key =
    "";
  /* global
       target_address:
         writable */
  target_address =
    "";
  /* global
       display_unit:
         writable */
  display_unit =
    "";
  /* global
       output_type:
         writable */
  output_type =
    "";
  /* global
       output_file:
         writable */
  output_file =
    "";
  /* global
       retries_max:
         writable */
  retries_max =
    "";
  quiet =
    "";
}

async function
  _price_gas_transaction_get(
    _target_network,
    _selection_mode,
    _api_key_path,
    _display_unit,
    _wallet_seed,
    _target_address,
    _output_file,
    _retries_max) {
  let
    _fee_data,
    _msg,
    _price_gas,
    _price_gas_target,
    _price_gas_get_args,
    _provider_get_opts,
    _retry,
    _request,
    _success,
    _wallet_dir,
    _wallet_password,
    _wallet_path_list;
  _price_gas_get_args =
    [];
  if ( typeof(
         _selection_mode) == 'undefined' ||
       _selection_mode == "" ) {
    _selection_mode =
      "auto";
    _msg =
      "No selection mode set. " +
      `Setting '${_selection_mode}'.`;
    _msg_info(
      _msg);
  }
  if ( typeof(
         _output_type) == 'undefined' ||
       _output_type == "" ) {
    _output_type =
      "price";
  }
  if ( typeof(
         _retries_max) == 'undefined' ||
       _retries_max == "" ) {
    _retries_max =
      3;
  }
  else {
    _retries_max =
      Number(
        _retries_max);
  }
  if ( typeof(
         _display_unit) == 'undefined' ||
       _display_unit == "" ) {
    _display_unit =
      "ether";
  }
  _timeout =
    100000;
  _retry =
    0;
  _success =
    false;
  _wallet_password =
    "";
  _wallet_dir =
    _dirname(
      _wallet_seed);
  _wallet_path_list = [
    _wallet_dir,
    "wallet.dat"
  ];
  _wallet_path =
    _path_join(
      _wallet_path_list);
  _provider_get_opts = [
    _target_network,
  ];
  if ( _output_file == undefined ) {
    _output_file =
      "";
  }
  if ( _api_key_path != "" ) {
    _api_key =
      _file_read(
        _api_key_path);
    _provider_get_opts.push(
      _api_key);
  }
  _provider_get_opts.push(
    _timeout);
  _provider =
    await _provider_get.apply(
      null,
      _provider_get_opts);
  _msg_info_provider_generated(
    _provider);
  // if ( _target_address == "" ) {
  //   _wallet_get_opts = [
  //     _wallet_path,
  //     _wallet_password,
  //     _wallet_seed,
  //     _provider
  //   ];
  //   _wallet =
  //     _wallet_get.apply(
  //       null,
  //       _wallet_get_opts);
  //   _target_address =
  //     _wallet.address;
  // }
  while ( _success == false &&
          _retry < _retries_max ) {
    try {
      _price_gas_get_args.push(
        _target_network,
        _api_key_path,
        _display_unit,
        _wallet_seed,
        _target_address,
        _output_type,
        "", // Output file
        _retries_max);
      _price_gas = await
        _price_gas_get.apply(
          null,
          _price_gas_get_args);
      _msg =
        `Got gas price '${_price_gas}' ${_display_unit} ` +
        `of output type '${_output_type}' ` +
        `for network '${_target_network}'.`;
      _msg_info(
        _msg);
      _price_gas =
        Number(
          _price_gas);
      if ( _selection_mode == "auto" ) {
        _selection_mode =
          "rpc";
      }
      if ( _selection_mode == "simple" ) {
        _price_gas_target =
          Math.floor(
            _price_gas * 12 / 10);
      }
      else if ( _selection_mode == "fast" ) {
        _price_gas_target =
          Math.floor(
            _price_gas * 20 / 10 );
      }
      else if ( _selection_mode == "nextblock" ) {
        _price_gas_target =
          Math.floor(
            _price_gas * 50 / 10 );
      }
      else if ( _selection_mode == "rpc" ) {
        _price_gas_target =
          _price_gas;
      }
      else {
        _msg =
          `Unknown selection mode '${_selection_mode}'.`;
        _msg_error(
          _msg,
          1);
      }
      if ( _output_file != "" ) {
          _file_write(
            _output_file,
            _price_gas_target.toString());
      }
      _success =
        true;
    } catch(
        _err) {
      _retry =
        _retry + 1;
      _msg =
        `Error retrieving gas price, ` +
	`retrying (${_retry} of ${_retries_max})`;
      console.error(
        _err);
      _msg_error(
        _msg,
        0);
      await _sleep(
        3000);
    }
  }
  if ( _success == false &&
       _retry == _retries_max ) {
    throw "Error retrieving balance.";
  }
  return _price_gas_target;
}

function
  _overrides_set() {
  _override_set(
    "selection",
    "mode",
    "simple");
  _override_set(
    "display",
    "unit",
    "wei");
  _override_set(
    "output",
    "type",
    "price");
  _override_set(
    "retries",
    "max",
    "1");
}

function
  _config_show() {
  let
    _line;
  const
    _text = [
      `${app_name} configuration:`,
      `         Display unit: ${display_unit}`,
      `       Selection mode: ${selection_mode}`,
      `          Output type: ${output_type}`,
      `          Output file: ${output_file}`,
      `Credentials options:`,
      `          Wallet seed: ${wallet_seed}`,
      `       Target address: ${target_address}`,
      `    Network options:`,
      `       Target network: ${target_network}`,
      `              API Key: ${api_key}`,
      `      Maximum retries: ${retries_max}`
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage(
    _exit_code) {
  let
    _line,
    _text;
  _text = [
    "Usage:",
    "  price-gas-transaction-get",
    "    <quiet>",
    "    <target-network>",
    "    (<selection-mode>)",
    "    (<api-keys-path)",
    "    (<display-unit>)",
    "    (<seed-path>)",
    "    (<target-address>)",
    "    (<output-type>)",
    "    (<output-file>)",
    "    (<retries-max>)",
    "",
    "Arguments:",
    "  <target-network>    Name of the network to connect to.",
    "  <selection-mode>    Can be 'simple'.",
    `                      Default: '${selection_mode}'`,
    "",
    "Optional arguments:",
    "  <api-key-path>      Path on disk of the API key for",
    "                      the network service provider.",
    "  <display-unit>      Can be 'wei' or 'ether'.",
    `                      Default: '${display_unit}'`,
    "  <seed-path>         Path on disk of the file",
    "                      containing the seed phrase.",
    "  <target-address>    Address for which to return",
    "                      the gas price (not used).",
    "                      Default: the wallet address.",
    "                      corresponding to the seed.",
    "  <output-type>       Type of price output to return.",
    `                      Default: '${output_type}'`,
    "  <output-file>       File in which to save the balance.",
    `                      Default: '${output_file}'`,
    "  <retries-max>       Maximum number of retries.",
    `                      Default: ${retries_max}`,
  ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  _exit(
    _exit_code);
}


function _cmdline_parse() {
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        target_network =
          _value;
      }
      if ( _index == 4 ) {
        selection_mode =
          _value;
      }
      if ( _index == 5 ) {
        api_key =
          _value;
      }
      if ( _index == 6 ) {
        display_unit =
          _value;
      }
      if ( _index == 7 ) {
        target_address =
          _value;
      }
      if ( _index == 8 ) {
        wallet_seed =
          _value;
      }
      if ( _index == 9 ) {
        output_type =
          _value;
      }
      if ( _index == 10 ) {
        output_file =
          _value;
      }
      if ( _index == 11 ) {
        retries_max =
          _value;
      }
      if ( _value == "-h" ||
           _value == "--help" ) {
        quiet =
          "n";
        _usage(
          0);
      }
  });
  if ( target_network == "" ) {
    _msg =
      "No input network given."
    _msg_error(
      _msg,
      1);
    _overrides_set();
    _usage(
      1);
  }
}

async function
  _price_gas_transaction_get_cmdline(
    _app_opts) {
  let
    _price_gas;
  try {
    _price_gas =
      await _price_gas_transaction_get.apply(
        null,
        _app_opts);
    console.log(
      _price_gas.toString());
    // process.stdout.write(
    //   _balance.toString());
  }
  catch(
    _error) {
    _msg_error(
      _error,
      1);
  }
}

if ( await _cmdline_check(
       "price-gas-transaction-get") ) {
  _global_variables();
  _cmdline_parse();
  _config_show();
  app_opts = [
    target_network,
    selection_mode,
    api_key,
    display_unit,
    wallet_seed,
    target_address,
    output_type,
    output_file,
    retries_max
  ];
  _price_gas_transaction_get_cmdline(
    app_opts);
}

module.exports = {
  _price_gas_transaction_get:
    _price_gas_transaction_get
};
