#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     seed-new
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public
 *     License along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

/* Crash Javascript global variables */

/* global
     quiet:
       writable */

const
  _libcrash =
    require(
      "crash-js");
/* global
     _dirname */
const
  _dirname =
    _libcrash._dirname;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _file_exists */
const
  _file_exists =
    _libcrash._file_exists;
/* global
     _file_write */
const
  _file_write =
    _libcrash._file_write;
/* global
     _msg_info */
const
  _msg_info = 
    _libcrash._msg_info;
/* global
     _msg_info_obj */
const
  _msg_info_obj = 
    _libcrash._msg_info_obj;
/* global
     _msg_error */
const
 _msg_error = 
   _libcrash._msg_error;
/* global
     _require */
const
  _require =
    _libcrash._require;
const
  _ethers_module =
    await _require(
      "ethers");
/* global
     _ethers */
_ethers = 
  _ethers_module.ethers;
/* global
     _wallet_class */
const
  _wallet_class =
    _ethers.Wallet;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "seed-new";
  /* global
       seed_path:
         writable */
  seed_path =
    "";
  quiet =
    "";
}

function
  _dir_missing_error(
    _dir) {
  const
    _msg =
      `The directory '${_dir}' does not exist.`;
  _msg_error(
    _msg,
    1)
}

function
  _msg_info_seed_write(
    _path) {
  const
    _msg =
      `Writing seed to '${_path}'.`;
  _msg_info(
    _msg);
}

function
  _msg_info_seed_written(
    _path) {
  const
    _msg =
      `Seed written to '${_path}'.`;
  _msg_info(
    _msg);
}

function
  _mkseed(
    _path) {
  const
    _wallet =
      _wallet_class.createRandom();
  const
    _phrase =
      _wallet.mnemonic.phrase;
  if ( _path != "" ) {
    const
      _dir =
        _dirname(
          _path);
    const
      _dir_exists =
        _file_exists(
          _dir);
    if ( ! _dir_exists ) {
      _dir_missing_error(
        _dir);
    }
    else {
      if ( quiet != "y" ) {
        _msg_info_seed_write(
          _path);
      }
    }
    _file_write(
      _path,
      _phrase);
    if ( quiet != "y" ) {
      _msg_info_seed_written(
        _path);
    }
  }
  else {
    console.log(
      _phrase);
  }
}

function
  _config_show() {
  let
    _line;
  const
    _text = [
      `${app_name} configuration:`,
      `        Seed path: ${seed_path}`,
    ]
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}


function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _text = [
      "Usage:",
      "  mkseed",
      "   ( <path> )",
      "   ( <verbose> )"
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
  _exit(
    _exit_code);
}

function
  _cmdline_parse() {
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        seed_path =
          _value;
      }
      if ( _index == 3 ) {
        quiet =
          _value;
      }
  });
  if ( seed_path == "-h" ) {
    _usage(
      0);
  }
}


if ( _cmdline_check(
       "seed-new") ||
     _cmdline_check(
       "mkseed")  ) {
  _global_variables();
  _cmdline_parse();
  app_opts = [
    seed_path
  ];
  _mkseed.apply(
    null,
    app_opts);
}

module.exports = {
  _mkseed:
    _mkseed
};

// console.log('wallet.address:', wallet.address)
// console.log('wallet.mnemonic.phrase:', wallet.mnemonic.phrase)
// console.log('wallet.privateKey:', wallet.privateKey)
