#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/* Crash Javascript global variables */

/* global
     quiet:
       writable */

const
  _libcrash =
    await import(
      "libcrash-js");
/* global
     _cmdline_check */
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _msg_info */
const
  _msg_info = 
    _libcrash._msg_info;
/* global
     _msg_info_obj */
const
  _msg_info_obj = 
    _libcrash._msg_info_obj;
/* global
     _msg_error */
const
  _msg_error = 
    _libcrash._msg_error;
/* global
     _override_set */
const
  _override_set = 
    _libcrash._override_set;
const
  _network_provider_module =
    await import(
      './network-provider');
/* global
     _provider_get */
_provider_get =
  _network_provider_module._provider_get;
const
  _wallet_get_module =
    await import(
      './wallet-get');
/* global
     _wallet_get */
_wallet_get =
  _wallet_get_module._wallet_get;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "wallet-new";
  /* global
       app_opts:
         writable */
  app_opts =
    [];
  /* global
       wallet_path:
         writable */
  wallet_path =
    "";
  /* global
       wallet_password:
         writable */
  wallet_password =
    "";
  /* global
       wallet_seed:
         writable */
  wallet_seed =
    "";
  /* global
       target_network:
         writable */
  target_network =
    "";
  /* global
       api_key_path:
         writable */
  api_key_path =
    "";
  quiet =
    "";
}

function
  _seed_missing_error(
    _seed) {
  const
    _msg =
      `The seed '${_seed}' does not exist.`;
  _msg_error(
    _msg,
    1)
}

async function
  _wallet_new(
    _path,
    _password,
    _seed,
    _network,
    _api_key_path) {
  let
    _password_show,
    _provider;
  _provider =
    await _provider_get(
      _network,
      _api_key_path);
  const
    _seed_type =
      typeof(
        _seed);
  if ( _seed_type == "string" ) {
    const
      _seed_phrase =
        _seed.split(" ");
    const
      _phrase_length =
        _seed_phrase.length
    if ( _phrase_length != 12 &&
         _phrase_length != 24 ) {
      _msg_info_obj(
        "Seed path",
        _seed);
    }
  }
  if ( _path != "" ) {
    _msg_info_obj(
      "Wallet path",
      _path);
  }
  _password_show =
    "";
  if ( _password != "" ) {
    _password_show =
      "****";
    _msg_info_obj(
      "Wallet password",
      _password_show);
  }
  _wallet =
    _wallet_get(
      _path,
      _password,
      _seed,
      _provider);
  return _wallet;
}

function
  _overrides_set() {
  _override_set(
    "target",
    "network",
    "gnosis");
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _text = [
      "Usage:",
      "  Returns a Wallet object.",
      "",
      "  wallet-new",
      "    <path>",
      "    <password>",
      "    <seed>",
      "    <network>",
      "    <api-key-path>",
      "    <quiet>",
      "",
      "Arguments:",
      "  <path>              Wallet path.",
      "  <password>          Wallet password path",
      "  <seed>              Seed file path.",
      "  <network>           Network RPC.",
      "  <api-key-path>      Path on disk of the API key for",
      "                      the network service provider.",
      "  <quiet>             Whether to display additional output.",
      `                      Default: ${quiet}`,
      ""
    ];
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
  if ( -1 < _exit ) {
    _exit(
      _exit_code);
  }
}

async function
  _wallet_new_cmdline(
    app_opts) {
  let
    _wallet;
  _wallet =
    await _wallet_new.apply(
      null,
      app_opts);
  console.log(
    _wallet);
}

function
  _cmdline_parse() {
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        wallet_path =
          _value;
      }
      if ( _index == 3 ) {
        wallet_password =
          _value;
      }
      if ( _index == 4 ) {
        wallet_seed =
          _value;
      }
      if ( _index == 5 ) {
        target_network =
          _value;
      }
      if ( _index == 6 ) {
        api_key_path =
          _value;
      }
      if ( _index == 6 ) {
        quiet =
          _value;
      }
  });
  if ( wallet_path == "" ) {
    const
      _msg =
        "No wallet path specified.";
    _msg_error(
      _msg,
      0);
    _usage(
      1);
  }
}


if ( await _cmdline_check(
       "wallet-new") ) {
  _global_variables();
  await _cmdline_parse();
  await _overrides_set();
  app_opts=[
    wallet_path,
    wallet_password,
    wallet_seed,
    target_network,
    api_key_path,
    quiet
  ];
  _wallet_new_cmdline(
    app_opts);
}

export {
  _wallet_new
};

// module.exports = {
//   _wallet_new:
//     _wallet_new
// };
