#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

const
  _libcrash =
    require(
      "crash-js");
const
  _cmdline_check =
    _libcrash._cmdline_check;
/* global
     _exit */
const
  _exit =
    _libcrash._exit;
/* global
     _msg_info */
const
  _msg_info = 
    _libcrash._msg_info;
/* global
     _msg_info_obj */
const
  _msg_info_obj = 
    _libcrash._msg_info_obj;
/* global
     _msg_error */
const
  _msg_error = 
    _libcrash._msg_error;
/* global
     _file_exists */
const
  _file_exists =
    _libcrash._file_exists;
/* global
     _file_read */
const
  _file_read =
    _libcrash._file_read;
/* global
     _require */
const
  _require =
    _libcrash._require;
const
  _ethers_module =
    _require(
      "ethers");
/* global
     _ethers */
const 
  _ethers = 
    _ethers_module.ethers;
/* global
     _hdnode_wallet */
const
  _hdnode_wallet =
    _ethers.HDNodeWallet;

function
  _global_variables() {
  /* global
       app_name */
  app_name =
    "wallet-get";
  /* global
       app_opts */
  app_opts =
    [];
}


function _wallet_exists(
  _path) {
  let
    _exists,
    _msg; 
  _exists =
    _file_exists(
      _path);
  if ( _exists == true ) {
    const
      _msg =
        `Wallet '${_path}' already exists.`;
    const
      _error = {
        "error":
          _msg };
    throw _error;
  }
}

function
  _msg_error_seed_empty(
    _seed) {
  let
    _msg;
  _msg =
    `The seed '${_seed}' is empty.`;
  _msg_error(
    _msg,
    1)
}

function
  _msg_info_seed_loaded(
    _seed,
    _seed_type) {
  let
    _msg_obj,
    _phrase_show;
  if ( _seed_type == "file" ) {
    _msg_obj =
      "Seed file";
    _phrase_show =
      _seed;
  }
  else if ( _seed_type == "string" ||
            _seed_type == "array" ) {
    _msg_obj =
      "Seed phrase";
    _phrase_show =
      "****";
  }
  _msg_info_obj(
    _msg_obj,
    _phrase_show);
}

function
  _seed_missing_error(
    _seed) {
  const
    _msg =
      `Seed has unspecified value '${_seed}'.`;
  const
    _error = {
      "error":
        _msg };
  _usage();
  throw _error;
}

function
  _phrase_get(
    _seed) {
  let
    _seed_type,
    _seed_words;
  _seed_type =
    typeof(
      _seed);
  if ( _seed_type == "undefined" ||
       _seed == "" ||
       _seed == [] ) {
    _seed_missing_error(
      _seed);
  }
  else {
    const
      _seed_exists =
        _file_exists(
          _seed);
    if ( ! _seed_exists ) {
      if ( _seed_type == "string" ) {
        _seed_words =
          _seed.split(" ");
      }
      else if ( _seed_type == "object" ) {
        _seed_words =
          _seed;
      }
      else {
        _msg =
          `Unknown seed type '${_seed_type}'.`;
        _msg_error(
          _msg,
          1);
      }
      const
        _seed_is_phrase =
          _seed_words.length == 12 ||
          _seed_words.length == 24;
      if ( _seed_type == "string" &&
           _seed_is_phrase ) {
        _phrase =
          _seed;
      }
      else if ( _seed_type == "object" &&
                _seed_is_phrase ) {
        _phrase =
          _seed.join(" ");
      }
      else {
        _msg =
          `The seed '${_seed}' has type ` +
          `'${_seed_type}', ` +
          `it's not a valid path and it ` +
          `does not contain a valid phrase.`;
        const
          _error = {
            "error":
              _msg };
        throw _error;
      }
    }
    else {
      _seed_type =
        "file";
      _phrase =
        _file_read(
          _seed); 
      _seed_words =
        _phrase.split(" ")
      _seed_is_phrase =
        _seed_words.length == 12 ||
        _seed_words.length == 24;
      if ( ! _seed_is_phrase ) {
        _msg =
          `The seed phrase is encrypted, ` +
	  `OpenPGP on Ethereum decryption not implemented.`;
        _msg_error(
          _msg,
          1)
      }
    }
  }
  _msg_info_seed_loaded(
    _seed,
    _seed_type);
  return _phrase;
}

function
  _usage(
    _exit_code) {
  let
    _line;
  const
    _text = [
      "Returns a wallet object.",
      "",
      "  usage:",
      "    await _wallet_get(",
      "      _path",
      "      _password,",
      "      _seed,",
      "      _provider,",
      "      _wallet,",
      "      _verbose);",
      ""
    ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  _exit(
    _exit_code);
}

function _wallet_get(
  _path,
  _password,
  _seed,
  _provider,
  _wallet,
  _verbose) {
  let
    _password_show,
    _phrase_show,
    _seed_exists;
  _password_show =
    "";
  const
    _seed_type =
      typeof(
        _seed);
  const
    _wallet_type =
      typeof(
        _wallet);
  if ( typeof(
         _verbose) == "undefined" ||
       _verbose == "" ) {
    _verbose="n" 
  }
  if ( typeof(
         _password) == "undefined" ||
       _password != "" ) {
    _password_show="****" 
  }
  if ( ( _seed_type == "undefined" ||
         _seed == "" ||
         _seed == [] ) &&
       ( _wallet_type == "undefined" ||
         _wallet == "" ||
         _wallet == {} ) ) {
    _seed_missing_error(
      _seed);
  }
  if ( _verbose == "y" ) {
    _msg_info_obj(
      'Wallet path',
      _path);
    if ( _password_show != "" ) {
      _msg_info_obj(
        'Wallet password',
        _password_show);
    }
  }
  _wallet_exists(
    _path);
  const
    _phrase =
      _phrase_get(
        _seed);
  _wallet =
    _hdnode_wallet.fromPhrase(
      _phrase);
  _wallet.provider =
    _provider;
  _signer =
    _wallet.connect(
      _provider);
  return _signer;
}

if ( _cmdline_check(
       "wallet-get") ) {
  _global_variables();
}

module.exports = {
  _wallet_get:
    _wallet_get
};
